[spec]
paths = ["specs/api.md"]
url = "http://github.com/cryspen/libcrux-iot/blob/franziskus/proofs-and-reqs/libcrux-iot/sha3/"

[rust]
src = ["src/", "tests/"]

[lean]
# hax outputs extracted Lean files here (created by --run-hax)
lake_dir = "proofs/lean/"
proofs = ["proofs/lean/keccak_verification/implementation/"]

[hax]
# crate_dir defaults to this directory (next to Cargo.toml)
# extra_args = ["-i", "-** +req_fixture::*"]
