/-
  # `keccak.keccak_loop0` ↔ fold of `sponge.absorb_block`
                + sponge.absorb_rec unfold / fold characterization.

  This file delivers three artifacts:

  * `sponge_absorb_rec_unfold_short` / `sponge_absorb_rec_unfold_long`
    — pure one-step unfolds of the `partial_fixpoint`-defined
    `sponge.absorb_rec`. The short branch picks `absorb_final`; the
    long branch peels one full block via `absorb_block` and recurses
    on `message[rate..]`. Both are derived from
    `sponge.absorb_rec.eq_def` (auto-generated by `partial_fixpoint`).

  * `sponge_absorb_rec_eq_fold` — forward characterization. After
    `n = msg.length / rate` full blocks, `absorb_rec` equals a
    `Nat.fold` of `absorb_block` over those blocks followed by
    `absorb_final` on the remaining suffix. Proved by induction on
    `n`.

  * `keccak.keccak_loop0_spec` — the impl's outer "absorb full blocks"
    loop equals (in monadic-in-post form) `Nat.fold n absorb_block
    (init := .ok (lift s))`. Proved by `loop_range_spec_usize` with a
    fold-form invariant that threads both `r.i.val = 0` and the
    spec-fold lockstep.

  ## See also

  - `Sponge/AbsorbBlock.lean:keccak.absorb_block_spec` — per-block
    Triple used in the loop body.
  - `Equivalence/HacspecBridge.lean:loop_range_spec_usize`.
-/
import LibcruxIotSha3.Sponge.AbsorbBlock

open Aeneas Aeneas.Std Result Std.Do libcrux_iot_sha3 hacspec_sha3

namespace libcrux_iot_sha3.Sponge

set_option mvcgen.warning false

attribute [local spec] Aeneas.Std.uncurry

open libcrux_iot_sha3.Foundation libcrux_iot_sha3.Composition

-- Defensive seal re-issue: no proof in this file may unfold either side
-- of Bridge 1.
set_option allowUnsafeReducibility true in
attribute [local irreducible] keccak.keccakf1600 keccak_f.keccak_f

/-! ## `keccak.keccak_loop0` ↔ fold of `sponge.absorb_block`. -/

/-! ### Helper Triple: `RangeFromUsize` slice index.

This complements `core_models_Slice_Insts_index_RangeUsize_spec` in
`SliceSpecs.lean`. The `RangeFrom<Usize>` form is what `absorb_rec`'s
`message[rate..]` produces. -/
@[spec]
theorem core_models_Slice_Insts_index_RangeFromUsize_spec
    {T : Type} (s : Slice T) (r : CoreModels.core.ops.range.RangeFrom Std.Usize)
    (h : r.start.val ≤ s.val.length) :
    ⦃ ⌜ True ⌝ ⦄
    CoreModels.core.Slice.Insts.CoreOpsIndexIndex.index
      (CoreModels.core.ops.range.RangeFromUsize.Insts.CoreSliceIndexSliceIndexSliceSlice T) s r
    ⦃ ⇓ r' => ⌜ r'.val = s.val.drop r.start.val
                ∧ r'.val.length = s.val.length - r.start.val ⌝ ⦄ := by
  unfold CoreModels.core.Slice.Insts.CoreOpsIndexIndex.index
         CoreModels.core.ops.range.RangeFromUsize.Insts.CoreSliceIndexSliceIndexSliceSlice
         core.slice.index.Slice.index
         core.slice.index.SliceIndexRangeUsizeSlice.index
  have h0' : (⟨r.start, s.len⟩ : core.ops.range.Range Std.Usize).start
              ≤ (⟨r.start, s.len⟩ : core.ops.range.Range Std.Usize).end := by
    simpa [UScalar.le_equiv, Std.Slice.len, Std.Slice.length] using h
  have h1' : (⟨r.start, s.len⟩ : core.ops.range.Range Std.Usize).end.val
              ≤ (Std.Slice.length s) := by
    simp [Std.Slice.length, Std.Slice.len]
  simp only [Triple, WP.wp]
  simp [h0', Std.Slice.length, Std.Slice.len]
  refine ⟨?_, ?_⟩
  · unfold List.slice
    exact List.take_of_length_le (by simp)
  · unfold List.slice
    rw [List.length_take, List.length_drop]
    omega

/-! ### Local helpers (re-derived from `AbsorbBlock.lean`'s private versions). -/

private theorem triple_of_ok_abs {α : Type} {x : Result α} {v : α}
    {P : α → Prop} (hx : x = .ok v) (hp : P v) :
    ⦃ ⌜ True ⌝ ⦄ x ⦃ ⇓ r => ⌜ P r ⌝ ⦄ := by
  subst hx; simp [Std.Do.Triple, WP.wp, PredTrans.apply, hp]

private theorem triple_exists_ok_abs {α : Type} {x : Result α}
    {P : α → Prop}
    (h : ⦃ ⌜ True ⌝ ⦄ x ⦃ ⇓ r => ⌜ P r ⌝ ⦄) :
    ∃ v, x = .ok v ∧ P v := by
  match hx : x with
  | .ok v =>
      refine ⟨v, rfl, ?_⟩
      have := h; simp [Std.Do.Triple, WP.wp, PredTrans.apply] at this; exact this
  | .fail _ =>
      exfalso; have := h; simp [Std.Do.Triple, WP.wp, PredTrans.apply] at this
  | .div =>
      exfalso; have := h; simp [Std.Do.Triple, WP.wp, PredTrans.apply] at this

/-- Generalizes `loop_range_spec_usize` to asymmetric `cont`/`done` types.
    The `cont` branch carries `Range × β`; the `done` branch carries `γ`. -/
private theorem loop_range_spec_gen {β γ : Type}
    (body : (CoreModels.core.ops.range.Range Std.Usize × β) →
      Result (ControlFlow (CoreModels.core.ops.range.Range Std.Usize × β) γ))
    (init : β) (s e : Std.Usize)
    (inv : Std.Usize → β → Prop) (post : γ → Prop)
    (h_le : s.val ≤ e.val)
    (h_init : inv s init)
    (h_step : ∀ acc (i : Std.Usize), s.val ≤ i.val → i.val ≤ e.val →
      inv i acc →
      ⦃ ⌜ True ⌝ ⦄
      body ({ start := i, «end» := e }, acc)
      ⦃ ⇓ r => match r with
        | .cont (iter', acc') =>
          ⌜ i.val < e.val ∧ iter'.«end» = e ∧ iter'.start.val = i.val + 1
            ∧ inv iter'.start acc' ⌝
        | .done y => ⌜ post y ⌝ ⦄) :
    ⦃ ⌜ True ⌝ ⦄
    loop body ({ start := s, «end» := e }, init)
    ⦃ ⇓ r => ⌜ post r ⌝ ⦄ := by
  suffices gen : ∀ (n : Nat) (acc : β) (k : Std.Usize),
      e.val - k.val = n → s.val ≤ k.val → k.val ≤ e.val → inv k acc →
      ⦃ ⌜ True ⌝ ⦄ loop body ({ start := k, «end» := e }, acc)
      ⦃ ⇓ r => ⌜ post r ⌝ ⦄ by
    exact gen _ init s rfl (Nat.le_refl _) h_le h_init
  intro n
  induction n with
  | zero =>
    intro acc k hn hs_le hke hinv
    -- Extract body result and postcondition.
    -- We case-split on `v` so that the `match v` in the post can be evaluated
    -- before `simpa` unwraps the `.down` on each `⌜ ⌝` branch.
    have hb : ∃ v, body ({ start := k, «end» := e }, acc) = .ok v ∧
        (match v with
          | .cont (iter', acc') => k.val < e.val ∧ iter'.«end» = e
              ∧ iter'.start.val = k.val + 1 ∧ inv iter'.start acc'
          | .done y => post y) := by
      have hs := h_step acc k hs_le hke hinv
      match hx : body ({ start := k, «end» := e }, acc) with
      | .ok v =>
          refine ⟨v, rfl, ?_⟩
          have hhs := by rw [hx] at hs; simpa [Std.Do.Triple, WP.wp, PredTrans.apply] using hs
          match v with
          | .cont (iter', acc') => simpa using hhs
          | .done y => simpa using hhs
      | .fail _ =>
          exfalso; have := h_step acc k hs_le hke hinv
          simp [Std.Do.Triple, WP.wp, PredTrans.apply, hx] at this
      | .div =>
          exfalso; have := h_step acc k hs_le hke hinv
          simp [Std.Do.Triple, WP.wp, PredTrans.apply, hx] at this
    obtain ⟨r, hbody, hpost⟩ := hb
    rw [loop.eq_def, hbody]
    match r with
    | .cont (iter', acc') =>
      simp only at hpost; exact absurd hpost.1 (by omega)
    | .done y =>
      simp only at hpost
      exact triple_of_ok_abs rfl hpost
  | succ n ih =>
    intro acc k hn hs_le hke hinv
    have hb : ∃ v, body ({ start := k, «end» := e }, acc) = .ok v ∧
        (match v with
          | .cont (iter', acc') => k.val < e.val ∧ iter'.«end» = e
              ∧ iter'.start.val = k.val + 1 ∧ inv iter'.start acc'
          | .done y => post y) := by
      have hs := h_step acc k hs_le hke hinv
      match hx : body ({ start := k, «end» := e }, acc) with
      | .ok v =>
          refine ⟨v, rfl, ?_⟩
          have hhs := by rw [hx] at hs; simpa [Std.Do.Triple, WP.wp, PredTrans.apply] using hs
          match v with
          | .cont (iter', acc') => simpa using hhs
          | .done y => simpa using hhs
      | .fail _ =>
          exfalso; have := h_step acc k hs_le hke hinv
          simp [Std.Do.Triple, WP.wp, PredTrans.apply, hx] at this
      | .div =>
          exfalso; have := h_step acc k hs_le hke hinv
          simp [Std.Do.Triple, WP.wp, PredTrans.apply, hx] at this
    obtain ⟨r, hbody, hpost⟩ := hb
    rw [loop.eq_def, hbody]
    match r with
    | .done y =>
      simp only at hpost
      exact triple_of_ok_abs rfl hpost
    | .cont (iter', acc') =>
      simp only at hpost
      obtain ⟨hlt, hend, hstart, hinv'⟩ := hpost
      have hiter : iter' = { start := iter'.start, «end» := e } := by
        cases iter'; cases hend; rfl
      rw [hiter]
      exact ih acc' iter'.start (by rw [hstart]; omega) (by rw [hstart]; omega)
        (by rw [hstart]; omega) hinv'

/-! ### `sponge.absorb_rec` one-step unfold lemmas.

Two branches conditioned on `message.val.length < rate.val`. Each
branch reduces `eq_def`'s do-chain into a clean closed form. -/

/-- Build a `Slice U8` whose `.val` is `m.val.slice 0 rate.val`, valid
    when `rate.val ≤ m.val.length`. -/
private def head_block (m : Slice Std.U8) (rate : Std.Usize)
    (_h : rate.val ≤ m.val.length) : Slice Std.U8 :=
  ⟨m.val.slice 0 rate.val, by
    unfold List.slice
    rw [List.length_take, List.length_drop]
    have h_eq : m.val.length - 0 = m.val.length := by omega
    rw [h_eq]
    have := m.property; omega⟩

/-- Build a `Slice U8` whose `.val` is `m.val.drop rate.val`, valid
    when `rate.val ≤ m.val.length`. -/
private def tail_after (m : Slice Std.U8) (rate : Std.Usize)
    (h : rate.val ≤ m.val.length) : Slice Std.U8 :=
  ⟨m.val.drop rate.val, by
    rw [List.length_drop]
    have := m.property; omega⟩

/-- Short branch: `message.length < rate` ⇒ immediate `absorb_final`. -/
theorem sponge_absorb_rec_unfold_short
    (state : Std.Array Std.U64 25#usize) (rate : Std.Usize) (delim : Std.U8)
    (message : Slice Std.U8)
    (h_lt : message.val.length < rate.val) :
    sponge.absorb_rec state rate delim message =
      sponge.absorb_final state message 0#usize (Std.Slice.len message) rate delim := by
  rw [sponge.absorb_rec.eq_def]
  unfold CoreModels.core.slice.Slice.len
  have h_i_val : (Std.Slice.len message).val = message.val.length := by
    simp [Std.Slice.len]
  have h_lt' : Std.Slice.len message < rate := by
    show (Std.Slice.len message).val < rate.val
    rw [h_i_val]; exact h_lt
  show (do let i ← pure (Std.Slice.len message)
            if i < rate then sponge.absorb_final state message 0#usize i rate delim
            else _) = _
  simp only [pure_bind]
  rw [if_pos h_lt']

/-- Long branch: `message.length ≥ rate` ⇒ peel one block, recurse on
    `message[rate..]`. The result is presented as a clean do-block on
    `head_block` and `tail_after`. -/
theorem sponge_absorb_rec_unfold_long
    (state : Std.Array Std.U64 25#usize) (rate : Std.Usize) (delim : Std.U8)
    (message : Slice Std.U8)
    (h_ge : rate.val ≤ message.val.length) :
    sponge.absorb_rec state rate delim message =
      (sponge.absorb_block state (head_block message rate h_ge) rate >>=
        fun s' => sponge.absorb_rec s' rate delim (tail_after message rate h_ge)) := by
  rw [sponge.absorb_rec.eq_def]
  unfold CoreModels.core.slice.Slice.len
  have h_i_val : (Std.Slice.len message).val = message.val.length := by
    simp [Std.Slice.len]
  have h_not_lt : ¬ (Std.Slice.len message < rate) := by
    show ¬ ((Std.Slice.len message).val < rate.val)
    rw [h_i_val]; omega
  show (do let i ← pure (Std.Slice.len message)
            if i < rate then _
            else _) = _
  simp only [pure_bind]
  rw [if_neg h_not_lt]
  -- Reduce both slice index calls to concrete .ok values.
  have h_idx_range : CoreModels.core.Slice.Insts.CoreOpsIndexIndex.index
      (CoreModels.core.ops.range.RangeUsize.Insts.CoreSliceIndexSliceIndexSliceSlice Std.U8)
      message { start := 0#usize, «end» := rate }
    = .ok (head_block message rate h_ge) := by
    unfold CoreModels.core.Slice.Insts.CoreOpsIndexIndex.index
           CoreModels.core.ops.range.RangeUsize.Insts.CoreSliceIndexSliceIndexSliceSlice
           core.slice.index.Slice.index
           core.slice.index.SliceIndexRangeUsizeSlice.index
    have h_le_v : (0#usize : Std.Usize) ≤ rate := by
      show (0 : Nat) ≤ rate.val; exact Nat.zero_le _
    have h_rate : rate.val ≤ message.length := by simp [Std.Slice.length, h_ge]
    simp [h_le_v, h_rate]
    apply Subtype.ext
    rfl
  rw [h_idx_range]; simp only [bind_tc_ok]
  -- Now the tail slice index.
  have h_idx_from : CoreModels.core.Slice.Insts.CoreOpsIndexIndex.index
      (CoreModels.core.ops.range.RangeFromUsize.Insts.CoreSliceIndexSliceIndexSliceSlice Std.U8)
      message { start := rate }
    = .ok (tail_after message rate h_ge) := by
    unfold CoreModels.core.Slice.Insts.CoreOpsIndexIndex.index
           CoreModels.core.ops.range.RangeFromUsize.Insts.CoreSliceIndexSliceIndexSliceSlice
           core.slice.index.Slice.index
           core.slice.index.SliceIndexRangeUsizeSlice.index
    have h_le_v : ({ start := rate, «end» := message.len } : core.ops.range.Range Std.Usize).start
                    ≤ ({ start := rate, «end» := message.len } : core.ops.range.Range Std.Usize).end := by
      show rate.val ≤ message.len.val
      simp [Std.Slice.len, h_ge]
    have h_rate : ({ start := rate, «end» := message.len } : core.ops.range.Range Std.Usize).end.val
                    ≤ message.length := by
      simp [Std.Slice.length, Std.Slice.len]
    simp [h_le_v]
    apply Subtype.ext
    show message.val.slice rate.val message.len.val = message.val.drop rate.val
    unfold List.slice
    rw [show message.len.val = message.val.length from by simp [Std.Slice.len]]
    rw [List.take_of_length_le (by rw [List.length_drop])]
  -- The remaining goal: do { state1 ← absorb_block ...; let s1 ← .ok tail; absorb_rec state1 rate delim s1 }
  -- vs `absorb_block ... >>= fun s' => absorb_rec s' rate delim tail`.
  -- After substituting h_idx_from inside the inner bind...
  show (sponge.absorb_block state (head_block message rate h_ge) rate >>=
          fun state1 => do
            let s1 ← _
            sponge.absorb_rec state1 rate delim s1) = _
  congr 1
  ext s'
  rw [h_idx_from]
  simp only [bind_tc_ok]

/-! ### `sponge.absorb_rec` ↔ Nat.fold characterization.

A forward fold-form characterization: peeling `k` full blocks via
`absorb_rec` (each handled by its long-branch unfold) is equal to
`Nat.fold k` of `absorb_block` over those blocks, then `absorb_rec`
on the suffix `msg.drop (k*rate)`.

Used downstream by `absorb_final` to bridge `absorb_rec` with the impl's
forward-iteration loop. -/

/-- Pure `Nat.fold` form analogous to `absorb_fold` but parameterized
    by the spec-state directly (no `lift` indirection) and a `Slice U8`
    message. Identical body to `absorb_fold`. -/
def absorb_fold_spec (state : Std.Array Std.U64 25#usize)
    (msg : Slice Std.U8) (rate : Std.Usize) (k : Nat) :
    Result (Std.Array Std.U64 25#usize) :=
  Nat.fold k (init := (.ok state : Result _))
    (fun j _hj acc => acc >>= fun st =>
      sponge.absorb_block st
        ⟨msg.val.slice (j * rate.val) ((j + 1) * rate.val), by
          unfold List.slice
          rw [List.length_take, List.length_drop]
          have := msg.property; omega⟩ rate)

theorem sponge_absorb_rec_eq_fold
    (state : Std.Array Std.U64 25#usize) (rate : Std.Usize) (delim : Std.U8)
    (msg : Slice Std.U8) (k : Nat) (h_k : k * rate.val ≤ msg.val.length) :
    sponge.absorb_rec state rate delim msg =
      absorb_fold_spec state msg rate k >>= fun s_k =>
        sponge.absorb_rec s_k rate delim
          ⟨msg.val.drop (k * rate.val), by
            rw [List.length_drop]; have := msg.property; omega⟩ := by
  induction k generalizing state with
  | zero =>
    unfold absorb_fold_spec
    simp only [Nat.fold_zero, Nat.zero_mul, List.drop_zero]
    show sponge.absorb_rec state rate delim msg
       = .ok state >>= fun s_k =>
            sponge.absorb_rec s_k rate delim ⟨msg.val, _⟩
    simp only [bind_tc_ok]
    congr 1
  | succ k ih =>
    -- Step shape:
    -- IH gives:
    --   absorb_rec state rate delim msg
    --     = absorb_fold_spec state msg rate k >>= λ s_k =>
    --         absorb_rec s_k rate delim msg.drop (k*rate)
    -- Then we apply unfold_long to the inner absorb_rec on msg.drop(k*rate).
    -- Finally, fold_succ exposes the (k+1)-th absorb_block on the RHS.
    have h_k_le : k * rate.val ≤ msg.val.length := by
      have h1 : k * rate.val ≤ (k + 1) * rate.val := by
        apply Nat.mul_le_mul_right; omega
      omega
    rw [ih state h_k_le]
    -- Now goal: absorb_fold_spec state msg rate k >>= λ s_k => absorb_rec s_k rate delim ⟨msg.drop (k*rate), _⟩
    --        = absorb_fold_spec state msg rate (k+1) >>= λ s_{k+1} => absorb_rec s_{k+1} rate delim ⟨msg.drop ((k+1)*rate), _⟩.
    -- absorb_fold_spec (k+1) = absorb_fold_spec k >>= (absorb_block at index k) (by Nat.fold_succ).
    -- And absorb_rec s_k rate delim ⟨msg.drop (k*rate), _⟩ unfolds (long) to
    -- absorb_block s_k (msg.slice (k*rate) ((k+1)*rate)) rate >>= λ s' => absorb_rec s' rate delim ⟨msg.drop ((k+1)*rate), _⟩.
    unfold absorb_fold_spec
    rw [Nat.fold_succ]
    -- Now RHS-fold (k+1) becomes: absorb_block_step k >>= (Nat.fold k inner).
    -- BUT Nat.fold_succ peels from the END (top-level application is at index k).
    -- Result: Nat.fold (k+1) f init = f k _ (Nat.fold k f init)
    -- So absorb_fold_spec (k+1) = (absorb_fold_spec k) >>= absorb_block_at_k.
    -- bind_assoc gives:
    --   (absorb_fold_spec k >>= absorb_block_at_k) >>= λ s_{k+1} => absorb_rec s_{k+1} ...
    -- = absorb_fold_spec k >>= λ s_k => (absorb_block_at_k s_k >>= λ s_{k+1} => absorb_rec s_{k+1} ...)
    -- So we need to show the inner bind LHS = RHS:
    --   absorb_rec s_k rate delim ⟨msg.drop (k*rate), _⟩
    --   = absorb_block_at_k s_k >>= λ s_{k+1} => absorb_rec s_{k+1} rate delim ⟨msg.drop ((k+1)*rate), _⟩.
    rw [bind_assoc]
    -- Goal now: bind acc f1 = bind acc f2, where acc = absorb_fold_spec k, and f1 = ..., f2 = ....
    congr 1
    ext s_k
    -- Now goal: absorb_rec s_k rate delim ⟨msg.drop (k*rate), _⟩
    --       = absorb_block s_k ⟨msg.slice (k*rate) ((k+1)*rate), _⟩ rate >>= fun s' =>
    --           absorb_rec s' rate delim ⟨msg.drop ((k+1)*rate), _⟩.
    -- Apply unfold_long to the LHS, with msg_tail := msg.drop (k*rate).
    -- The precondition: rate ≤ msg_tail.length, which follows from (k+1)*rate ≤ msg.length.
    have h_drop_len : (msg.val.drop (k * rate.val)).length = msg.val.length - k * rate.val := by
      rw [List.length_drop]
    have h_rate_drop : rate.val ≤ (msg.val.drop (k * rate.val)).length := by
      rw [h_drop_len]
      have h_eq : (k + 1) * rate.val = k * rate.val + rate.val := by ring
      have := h_k
      omega
    -- Build the tail-message slice for the unfold_long argument.
    set msg_tail : Slice Std.U8 :=
      ⟨msg.val.drop (k * rate.val), by
        rw [List.length_drop]; have := msg.property; omega⟩ with h_msg_tail_def
    have h_tail_len : msg_tail.val.length = msg.val.length - k * rate.val := h_drop_len
    have h_rate_tail : rate.val ≤ msg_tail.val.length := h_rate_drop
    rw [sponge_absorb_rec_unfold_long s_k rate delim msg_tail h_rate_tail]
    -- Now LHS = absorb_block s_k (head_block msg_tail rate _) rate >>= λ s' =>
    --   absorb_rec s' rate delim (tail_after msg_tail rate _).
    -- We need to match this with RHS via the slice equalities:
    --   head_block msg_tail rate = msg.slice (k*rate) ((k+1)*rate) up to Subtype.
    --   tail_after msg_tail rate = msg.drop ((k+1)*rate) up to Subtype.
    have h_head_eq :
        (head_block msg_tail rate h_rate_tail).val
          = msg.val.slice (k * rate.val) ((k + 1) * rate.val) := by
      show msg_tail.val.slice 0 rate.val = _
      rw [show msg_tail.val = msg.val.drop (k * rate.val) from rfl]
      unfold List.slice
      rw [List.drop_zero]
      have h_sub_eq : (k + 1) * rate.val - k * rate.val = rate.val := by ring_nf; omega
      have h_sub_eq0 : rate.val - 0 = rate.val := by omega
      rw [h_sub_eq, h_sub_eq0]
    have h_tail_eq :
        (tail_after msg_tail rate h_rate_tail).val
          = msg.val.drop ((k + 1) * rate.val) := by
      show msg_tail.val.drop rate.val = _
      rw [show msg_tail.val = msg.val.drop (k * rate.val) from rfl]
      rw [List.drop_drop]
      have h_add_eq : k * rate.val + rate.val = (k + 1) * rate.val := by ring
      rw [h_add_eq]
    -- Now combine: absorb_block s_k (head_block msg_tail rate _) rate
    --   = absorb_block s_k ⟨msg.slice (k*rate) ((k+1)*rate), _⟩ rate.
    have h_block_arg :
        head_block msg_tail rate h_rate_tail
          = (⟨msg.val.slice (k * rate.val) ((k + 1) * rate.val), by
              unfold List.slice
              rw [List.length_take, List.length_drop]
              have := msg.property; omega⟩ : Slice Std.U8) := by
      apply Subtype.ext; exact h_head_eq
    rw [h_block_arg]
    -- The remaining `absorb_rec _ rate delim (tail_after msg_tail rate _)`
    -- needs `tail_after msg_tail rate _ = ⟨msg.drop ((k+1)*rate), _⟩`.
    congr 1
    ext s'
    congr 1
    apply Subtype.ext
    exact h_tail_eq

/-! ### `keccak.keccak_loop0_spec` — impl loop ↔ Nat.fold of `sponge.absorb_block`.

The post: termination (impl returns `.ok r`), `r.i.val = 0`, and the
spec-side fold equation

  `Nat.fold n.val (init := .ok (lift s)) (fun j _ acc => acc.bind fun st =>
      sponge.absorb_block st (data.slice (j*RATE) ((j+1)*RATE)) RATE)
   = .ok (lift r)`.

Proved by `loop_range_spec_usize` with the natural fold-invariant:
at iteration `k`, the impl state's `i.val = 0` AND the first `k` block
absorb_blocks have already produced `lift state'`. -/

/-- The fold-form invariant accumulator for `keccak_loop0`. At iteration
    `k`, this is the `Nat.fold` over the first `k` block-absorb_block
    calls on the spec side.

    We use a fixed `Slice.U8` argument constructed from `data.val.slice`
    plus a permissive length proof (`≤ data.val.length`, no need to know
    `j*RATE + RATE ≤ data.length`). If the slice is out-of-range for any
    `j`, `absorb_block` will fail — but the impl-side loop only iterates
    `j < n` so the relevant `j`'s are always in range. -/
def absorb_fold (s : state.KeccakState) (data : Slice Std.U8)
    (RATE : Std.Usize) (k : Nat) :
    Result (Std.Array Std.U64 25#usize) :=
  Nat.fold k (init := (.ok (Foundation.lift s) : Result _))
    (fun j _hj acc => acc >>= fun st =>
      sponge.absorb_block st
        ⟨data.val.slice (j * RATE.val) ((j + 1) * RATE.val), by
          unfold List.slice
          rw [List.length_take, List.length_drop]
          have := data.property; omega⟩ RATE)

/-- Bridge: `absorb_fold` (impl-side, parameterized by `KeccakState`) and
    `absorb_fold_spec` (spec-side, parameterized by `Array U64 25`) are the
    same fold when the initial spec state is `lift s`. -/
theorem absorb_fold_eq_spec
    (s : state.KeccakState) (data : Slice Std.U8) (RATE : Std.Usize) (k : Nat) :
    absorb_fold s data RATE k
      = absorb_fold_spec (Foundation.lift s) data RATE k := by
  unfold absorb_fold absorb_fold_spec
  rfl

@[spec]
theorem keccak.keccak_loop0_spec
    (RATE : Std.Usize) (s : state.KeccakState) (data : Slice Std.U8)
    (n : Std.Usize)
    (h_i : s.i.val = 0)
    (h_RATE_mod : RATE.val % 8 = 0)
    (h_RATE_bnd : RATE.val ≤ 200)
    (h_n_RATE : n.val * RATE.val ≤ data.val.length)
    (h_off : n.val * RATE.val ≤ Std.Usize.max) :
    ⦃ ⌜ True ⌝ ⦄
    keccak.keccak_loop0 RATE { start := 0#usize, «end» := n } data s 0#usize
    ⦃ ⇓ r => ⌜ r.i.val = 0
              ∧ absorb_fold s data RATE n.val = .ok (Foundation.lift r) ⌝ ⦄ := by
  unfold keccak.keccak_loop0
  -- Apply the generalized loop spec with accumulator β = KeccakState × Usize,
  -- result γ = KeccakState.  The `start` field in the accumulator tracks
  -- the byte offset so the body no longer needs `k * RATE`.
  apply loop_range_spec_gen
      (inv := fun k (acc : state.KeccakState × Std.Usize) =>
          acc.1.i.val = 0
          ∧ acc.2.val = k.val * RATE.val
          ∧ absorb_fold s data RATE k.val = .ok (Foundation.lift acc.1))
      (post := fun r =>
          r.i.val = 0 ∧ absorb_fold s data RATE n.val = .ok (Foundation.lift r))
  · -- h_le: 0 ≤ n
    exact Nat.zero_le _
  · -- h_init: invariant holds at k = 0 with acc = (s, 0#usize).
    refine ⟨h_i, ?_, ?_⟩
    · simp
    · unfold absorb_fold; rfl
  · -- h_step: invariant is preserved by one loop body execution.
    intro ⟨s_k, start_k⟩ k h_ge h_le_k ⟨h_acc_i, h_acc_start, h_fold_acc⟩
    unfold keccak.keccak_loop0.body
    apply Std.Do.Triple.bind _ _
      (IteratorRange_next_spec_usize k n
        (Q := PostCond.noThrow fun (oi : Option Std.Usize × _) => ⌜
          match oi.1 with
          | none => k.val ≥ n.val ∧
                    oi.2 = { start := k, «end» := n }
          | some i => i = k ∧ k.val < n.val ∧
                      oi.2.«end» = n ∧ oi.2.start.val = k.val + 1
        ⌝)
        (fun hlt s' hs' => by
          dsimp only [PostCond.noThrow, Std.Do.SPred.down_pure]
          exact ⟨rfl, hlt, rfl, hs'⟩)
        (fun hge => by
          dsimp only [PostCond.noThrow, Std.Do.SPred.down_pure]
          exact ⟨hge, rfl⟩))
    intro ⟨o, iter1⟩
    apply triple_imp_intro
    rcases o with _ | _
    · -- None: iterator exhausted, loop done.
      rintro ⟨hge, -⟩
      show ⦃⌜True⌝⦄ (Aeneas.Std.Result.ok (ControlFlow.done s_k) : Result _) ⦃_⦄
      have hk_eq : k.val = n.val := Nat.le_antisymm h_le_k hge
      apply Sponge.triple_of_ok_abs (v := s_k) rfl
      exact ⟨h_acc_i, by rw [← hk_eq]; exact h_fold_acc⟩
    · -- Some _: one absorb_block iteration.
      rintro ⟨-, hk_lt, hiter1_end, hiter1_start⟩
      -- Bound facts for the absorb_block call.
      have hk1_le_n : k.val + 1 ≤ n.val := hk_lt
      have hk1_RATE_le : (k.val + 1) * RATE.val ≤ n.val * RATE.val := by
        have := Nat.mul_le_mul_right RATE.val hk1_le_n; simpa using this
      have hk_RATE_data : start_k.val + RATE.val ≤ data.val.length := by
        rw [h_acc_start]
        have h2 : (k.val + 1) * RATE.val = k.val * RATE.val + RATE.val := by ring
        omega
      have hk_RATE_max : start_k.val + RATE.val ≤ Std.Usize.max := by
        rw [h_acc_start]
        have h2 : (k.val + 1) * RATE.val = k.val * RATE.val + RATE.val := by ring
        omega
      mvcgen
      all_goals (try scalar_tac)
      -- Invariant preservation VC.
      -- After mvcgen on the new body (absorb_block first, then start_k + RATE):
      --   r   : KeccakState  (absorb_block result)
      --   h   : r.i.val = 0 ∧ sponge.absorb_block ... = .ok (lift r)
      --   r_1 : Usize        (start_k + RATE result)
      --   h_1 : r_1.val = start_k.val + RATE.val  (scalar arithmetic)
      expose_names
      obtain ⟨h_r1_i, h_r1_spec⟩ := h
      refine ⟨hk_lt, hiter1_end, hiter1_start, ?_⟩
      refine ⟨h_r1_i, ?_, ?_⟩
      · -- r_1.val = (k+1) * RATE.val
        -- h_1 : r_1.val = start_k.val + RATE.val
        -- h_acc_start : start_k.val = k.val * RATE.val
        rw [hiter1_start]
        linarith [h_acc_start, h_1,
          show (k.val + 1) * RATE.val = k.val * RATE.val + RATE.val from by ring]
      · -- absorb_fold s data RATE iter1.start.val = .ok (lift r).
        rw [hiter1_start]
        unfold absorb_fold
        rw [Nat.fold_succ]
        have h_inner : (Nat.fold k.val (init := (.ok (Foundation.lift s) : Result _))
            (fun j _hj acc' => acc' >>= fun st =>
              sponge.absorb_block st
                ⟨data.val.slice (j * RATE.val) ((j + 1) * RATE.val), by
                  unfold List.slice
                  rw [List.length_take, List.length_drop]
                  have := data.property; omega⟩ RATE))
          = .ok (Foundation.lift s_k) := by
          have := h_fold_acc; unfold absorb_fold at this; exact this
        rw [h_inner]
        simp only [bind_tc_ok]
        -- Goal: absorb_block (lift s_k) ⟨data.slice (k*RATE) ((k+1)*RATE), _⟩ RATE = .ok (lift r).
        -- h_r1_spec uses block_of_blocks data start_k RATE _ with
        --   .val = data.slice start_k.val (start_k.val + RATE.val).
        -- Since start_k.val = k*RATE (h_acc_start), the slices are equal.
        convert h_r1_spec using 2
        apply Subtype.ext
        show data.val.slice (k.val * RATE.val) ((k.val + 1) * RATE.val)
             = data.val.slice start_k.val (start_k.val + RATE.val)
        rw [h_acc_start]
        congr 1; ring

end libcrux_iot_sha3.Sponge
