name = "LibcruxIotMlKem"
version = "0.1.0"
defaultTargets = ["LibcruxIotMlKem"]

[[lean_lib]]
name = "LibcruxIotMlKem"

[[require]]
name = "Hax"
git = { url = "ssh://git@github.com/cryspen/hax-evit", subDir = "hax-lib/proof-libs/aeneas-lean" }
rev = "ffdf432705d409b62ec025d253a340234b59766f"

[[require]]
name = "HacspecMlKem"
git = { url = "https://github.com/cryspen/libcrux", subDir = "specs/ml-kem/proofs/aeneas-lean" }
rev = "a4cfb1ebf26431b2ee81f0dc19383158aaf397b7"
