-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [libcrux_iot_ml_kem]
import Aeneas
import CoreModels
open core_models
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace libcrux_iot_ml_kem

/-- [libcrux_iot_ml_kem::constants::COEFFICIENTS_IN_RING_ELEMENT]
    Source: 'ml-kem/src/constants.rs', lines 5:0-5:59 -/
@[global_simps, irreducible]
def constants.COEFFICIENTS_IN_RING_ELEMENT : Std.Usize := 256#usize

/-- Trait declaration: [libcrux_iot_ml_kem::vector::traits::Repr]
    Source: 'ml-kem/src/vector/traits.rs', lines 22:0-22:17
    Visibility: public -/
structure vector.traits.Repr (Self : Type) where

/-- Trait declaration: [libcrux_iot_ml_kem::vector::traits::Operations]
    Source: 'ml-kem/src/vector/traits.rs', lines 25:0-164:1
    Visibility: public -/
structure vector.traits.Operations (Self : Type) where
  core_modelsmarkerCopyInst : core_models.marker.Copy Self
  core_modelscloneCloneInst : core_models.clone.Clone Self
  ReprInst : vector.traits.Repr Self
  ZERO : Result Self
  from_i16_array : Slice Std.I16 → Self → Result Self
  reducing_from_i32_array : Slice Std.I32 → Self → Result Self
  add : Self → Self → Result Self
  sub : Self → Self → Result Self
  negate : Self → Result Self
  multiply_by_constant : Self → Std.I16 → Result Self
  bitwise_and_with_constant : Self → Std.I16 → Result Self
  shift_right : forall (SHIFT_BY : Std.I32), Self → Result Self
  cond_subtract_3329 : Self → Result Self
  barrett_reduce : Self → Result Self
  montgomery_multiply_by_constant : Self → Std.I16 → Result Self
  compress_1 : Self → Result Self
  compress : forall (COEFFICIENT_BITS : Std.I32), Self → Result Self
  decompress_ciphertext_coefficient : forall (COEFFICIENT_BITS : Std.I32), Self
    → Result Self
  ntt_layer_1_step : Self → Std.I16 → Std.I16 → Std.I16 → Std.I16 →
    Result Self
  ntt_layer_2_step : Self → Std.I16 → Std.I16 → Result Self
  ntt_layer_3_step : Self → Std.I16 → Result Self
  inv_ntt_layer_1_step : Self → Std.I16 → Std.I16 → Std.I16 → Std.I16
    → Result Self
  inv_ntt_layer_2_step : Self → Std.I16 → Std.I16 → Result Self
  inv_ntt_layer_3_step : Self → Std.I16 → Result Self
  accumulating_ntt_multiply : Self → Self → Slice Std.I32 → Std.I16 →
    Std.I16 → Std.I16 → Std.I16 → Result (Slice Std.I32)
  accumulating_ntt_multiply_fill_cache : Self → Self → Slice Std.I32 →
    Self → Std.I16 → Std.I16 → Std.I16 → Std.I16 → Result ((Slice
    Std.I32) × Self)
  accumulating_ntt_multiply_use_cache : Self → Self → Slice Std.I32 →
    Self → Result (Slice Std.I32)
  serialize_1 : Self → Slice Std.U8 → Result (Slice Std.U8)
  deserialize_1 : Slice Std.U8 → Self → Result Self
  serialize_4 : Self → Slice Std.U8 → Result (Slice Std.U8)
  deserialize_4 : Slice Std.U8 → Self → Result Self
  serialize_5 : Self → Slice Std.U8 → Result (Slice Std.U8)
  deserialize_5 : Slice Std.U8 → Self → Result Self
  serialize_10 : Self → Slice Std.U8 → Result (Slice Std.U8)
  deserialize_10 : Slice Std.U8 → Self → Result Self
  serialize_11 : Self → Slice Std.U8 → Result (Slice Std.U8)
  deserialize_11 : Slice Std.U8 → Self → Result Self
  serialize_12 : Self → Slice Std.U8 → Result (Slice Std.U8)
  deserialize_12 : Slice Std.U8 → Self → Result Self
  rej_sample : Slice Std.U8 → Slice Std.I16 → Result (Std.Usize × (Slice
    Std.I16))

/-- [libcrux_iot_ml_kem::polynomial::PolynomialRingElement]
    Source: 'ml-kem/src/polynomial.rs', lines 32:0-34:1 -/
structure polynomial.PolynomialRingElement (Vector : Type) where
  coefficients : Array Vector 16#usize

/-- [libcrux_iot_ml_kem::polynomial::ZETAS_TIMES_MONTGOMERY_R]
    Source: 'ml-kem/src/polynomial.rs', lines 5:0-17:2 -/
@[global_simps, irreducible]
def polynomial.ZETAS_TIMES_MONTGOMERY_R : Array Std.I16 128#usize :=
  Array.make 128#usize [
    (-1044)#i16, (-758)#i16, (-359)#i16, (-1517)#i16, 1493#i16, 1422#i16,
    287#i16, 202#i16, (-171)#i16, 622#i16, 1577#i16, 182#i16, 962#i16,
    (-1202)#i16, (-1474)#i16, 1468#i16, 573#i16, (-1325)#i16, 264#i16, 383#i16,
    (-829)#i16, 1458#i16, (-1602)#i16, (-130)#i16, (-681)#i16, 1017#i16,
    732#i16, 608#i16, (-1542)#i16, 411#i16, (-205)#i16, (-1571)#i16, 1223#i16,
    652#i16, (-552)#i16, 1015#i16, (-1293)#i16, 1491#i16, (-282)#i16,
    (-1544)#i16, 516#i16, (-8)#i16, (-320)#i16, (-666)#i16, (-1618)#i16,
    (-1162)#i16, 126#i16, 1469#i16, (-853)#i16, (-90)#i16, (-271)#i16, 830#i16,
    107#i16, (-1421)#i16, (-247)#i16, (-951)#i16, (-398)#i16, 961#i16,
    (-1508)#i16, (-725)#i16, 448#i16, (-1065)#i16, 677#i16, (-1275)#i16,
    (-1103)#i16, 430#i16, 555#i16, 843#i16, (-1251)#i16, 871#i16, 1550#i16,
    105#i16, 422#i16, 587#i16, 177#i16, (-235)#i16, (-291)#i16, (-460)#i16,
    1574#i16, 1653#i16, (-246)#i16, 778#i16, 1159#i16, (-147)#i16, (-777)#i16,
    1483#i16, (-602)#i16, 1119#i16, (-1590)#i16, 644#i16, (-872)#i16, 349#i16,
    418#i16, 329#i16, (-156)#i16, (-75)#i16, 817#i16, 1097#i16, 603#i16,
    610#i16, 1322#i16, (-1285)#i16, (-1465)#i16, 384#i16, (-1215)#i16,
    (-136)#i16, 1218#i16, (-1335)#i16, (-874)#i16, 220#i16, (-1187)#i16,
    (-1659)#i16, (-1185)#i16, (-1530)#i16, (-1278)#i16, 794#i16, (-1510)#i16,
    (-854)#i16, (-870)#i16, 478#i16, (-108)#i16, (-308)#i16, 996#i16, 991#i16,
    958#i16, (-1460)#i16, 1522#i16, 1628#i16
    ]

/-- [libcrux_iot_ml_kem::polynomial::zeta]:
    Source: 'ml-kem/src/polynomial.rs', lines 22:0-24:1
    Visibility: public -/
def polynomial.zeta (i : Std.Usize) : Result Std.I16 := do
  Array.index_usize polynomial.ZETAS_TIMES_MONTGOMERY_R i

/-- [libcrux_iot_ml_kem::ntt::ntt_at_layer_1]: loop body 0:
    Source: 'ml-kem/src/ntt.rs', lines 14:4-25:5 -/
@[rust_loop_body]
def ntt.ntt_at_layer_1_loop.body
  {Vector : Type} (vectortraitsOperationsInst : vector.traits.Operations
  Vector) (iter : core_models.ops.range.Range Std.Usize) (zeta_i : Std.Usize)
  (re : polynomial.PolynomialRingElement Vector) :
  Result (ControlFlow ((core_models.ops.range.Range Std.Usize) × Std.Usize ×
    (polynomial.PolynomialRingElement Vector)) (Std.Usize ×
    (polynomial.PolynomialRingElement Vector)))
  := do
  let (o, iter1) ←
    core_models.ops.range.Range.Insts.Core_modelsIterTraitsIteratorIterator.next
      Usize.Insts.Core_modelsIterRangeStep iter
  match o with
  | core_models.option.Option.None => ok (done (zeta_i, re))
  | core_models.option.Option.Some round =>
    let zeta_i1 ← zeta_i + 1#usize
    let (t, index_mut_back) ← Array.index_mut_usize re.coefficients round
    let i ← polynomial.zeta zeta_i1
    let i1 ← zeta_i1 + 1#usize
    let i2 ← polynomial.zeta i1
    let i3 ← zeta_i1 + 2#usize
    let i4 ← polynomial.zeta i3
    let i5 ← zeta_i1 + 3#usize
    let i6 ← polynomial.zeta i5
    let t1 ← vectortraitsOperationsInst.ntt_layer_1_step t i i2 i4 i6
    let a := index_mut_back t1
    ok (cont (iter1, i5, { coefficients := a }))

/-- [libcrux_iot_ml_kem::ntt::ntt_at_layer_1]: loop 0:
    Source: 'ml-kem/src/ntt.rs', lines 14:4-25:5 -/
@[rust_loop]
def ntt.ntt_at_layer_1_loop
  {Vector : Type} (vectortraitsOperationsInst : vector.traits.Operations
  Vector) (iter : core_models.ops.range.Range Std.Usize) (zeta_i : Std.Usize)
  (re : polynomial.PolynomialRingElement Vector) :
  Result (Std.Usize × (polynomial.PolynomialRingElement Vector))
  := do
  loop
    (fun (iter1, zeta_i1, re1) => ntt.ntt_at_layer_1_loop.body
      vectortraitsOperationsInst iter1 zeta_i1 re1)
    (iter, zeta_i, re)

/-- [libcrux_iot_ml_kem::ntt::ntt_at_layer_1]:
    Source: 'ml-kem/src/ntt.rs', lines 9:0-26:1 -/
@[reducible]
def ntt.ntt_at_layer_1
  {Vector : Type} (vectortraitsOperationsInst : vector.traits.Operations
  Vector) (zeta_i : Std.Usize) (re : polynomial.PolynomialRingElement Vector)
  (_initial_coefficient_bound : Std.Usize) :
  Result (Std.Usize × (polynomial.PolynomialRingElement Vector))
  := do
  ntt.ntt_at_layer_1_loop vectortraitsOperationsInst
    { start := 0#usize, «end» := 16#usize } zeta_i re

/-- [libcrux_iot_ml_kem::ntt::ntt_at_layer_2]: loop body 0:
    Source: 'ml-kem/src/ntt.rs', lines 35:4-44:5 -/
@[rust_loop_body]
def ntt.ntt_at_layer_2_loop.body
  {Vector : Type} (vectortraitsOperationsInst : vector.traits.Operations
  Vector) (iter : core_models.ops.range.Range Std.Usize) (zeta_i : Std.Usize)
  (re : polynomial.PolynomialRingElement Vector) :
  Result (ControlFlow ((core_models.ops.range.Range Std.Usize) × Std.Usize ×
    (polynomial.PolynomialRingElement Vector)) (Std.Usize ×
    (polynomial.PolynomialRingElement Vector)))
  := do
  let (o, iter1) ←
    core_models.ops.range.Range.Insts.Core_modelsIterTraitsIteratorIterator.next
      Usize.Insts.Core_modelsIterRangeStep iter
  match o with
  | core_models.option.Option.None => ok (done (zeta_i, re))
  | core_models.option.Option.Some round =>
    let zeta_i1 ← zeta_i + 1#usize
    let (t, index_mut_back) ← Array.index_mut_usize re.coefficients round
    let i ← polynomial.zeta zeta_i1
    let i1 ← zeta_i1 + 1#usize
    let i2 ← polynomial.zeta i1
    let t1 ← vectortraitsOperationsInst.ntt_layer_2_step t i i2
    let a := index_mut_back t1
    ok (cont (iter1, i1, { coefficients := a }))

/-- [libcrux_iot_ml_kem::ntt::ntt_at_layer_2]: loop 0:
    Source: 'ml-kem/src/ntt.rs', lines 35:4-44:5 -/
@[rust_loop]
def ntt.ntt_at_layer_2_loop
  {Vector : Type} (vectortraitsOperationsInst : vector.traits.Operations
  Vector) (iter : core_models.ops.range.Range Std.Usize) (zeta_i : Std.Usize)
  (re : polynomial.PolynomialRingElement Vector) :
  Result (Std.Usize × (polynomial.PolynomialRingElement Vector))
  := do
  loop
    (fun (iter1, zeta_i1, re1) => ntt.ntt_at_layer_2_loop.body
      vectortraitsOperationsInst iter1 zeta_i1 re1)
    (iter, zeta_i, re)

/-- [libcrux_iot_ml_kem::ntt::ntt_at_layer_2]:
    Source: 'ml-kem/src/ntt.rs', lines 30:0-45:1 -/
@[reducible]
def ntt.ntt_at_layer_2
  {Vector : Type} (vectortraitsOperationsInst : vector.traits.Operations
  Vector) (zeta_i : Std.Usize) (re : polynomial.PolynomialRingElement Vector)
  (_initial_coefficient_bound : Std.Usize) :
  Result (Std.Usize × (polynomial.PolynomialRingElement Vector))
  := do
  ntt.ntt_at_layer_2_loop vectortraitsOperationsInst
    { start := 0#usize, «end» := 16#usize } zeta_i re

/-- [libcrux_iot_ml_kem::ntt::ntt_at_layer_3]: loop body 0:
    Source: 'ml-kem/src/ntt.rs', lines 54:4-58:5 -/
@[rust_loop_body]
def ntt.ntt_at_layer_3_loop.body
  {Vector : Type} (vectortraitsOperationsInst : vector.traits.Operations
  Vector) (iter : core_models.ops.range.Range Std.Usize) (zeta_i : Std.Usize)
  (re : polynomial.PolynomialRingElement Vector) :
  Result (ControlFlow ((core_models.ops.range.Range Std.Usize) × Std.Usize ×
    (polynomial.PolynomialRingElement Vector)) (Std.Usize ×
    (polynomial.PolynomialRingElement Vector)))
  := do
  let (o, iter1) ←
    core_models.ops.range.Range.Insts.Core_modelsIterTraitsIteratorIterator.next
      Usize.Insts.Core_modelsIterRangeStep iter
  match o with
  | core_models.option.Option.None => ok (done (zeta_i, re))
  | core_models.option.Option.Some round =>
    let zeta_i1 ← zeta_i + 1#usize
    let (t, index_mut_back) ← Array.index_mut_usize re.coefficients round
    let i ← polynomial.zeta zeta_i1
    let t1 ← vectortraitsOperationsInst.ntt_layer_3_step t i
    let a := index_mut_back t1
    ok (cont (iter1, zeta_i1, { coefficients := a }))

/-- [libcrux_iot_ml_kem::ntt::ntt_at_layer_3]: loop 0:
    Source: 'ml-kem/src/ntt.rs', lines 54:4-58:5 -/
@[rust_loop]
def ntt.ntt_at_layer_3_loop
  {Vector : Type} (vectortraitsOperationsInst : vector.traits.Operations
  Vector) (iter : core_models.ops.range.Range Std.Usize) (zeta_i : Std.Usize)
  (re : polynomial.PolynomialRingElement Vector) :
  Result (Std.Usize × (polynomial.PolynomialRingElement Vector))
  := do
  loop
    (fun (iter1, zeta_i1, re1) => ntt.ntt_at_layer_3_loop.body
      vectortraitsOperationsInst iter1 zeta_i1 re1)
    (iter, zeta_i, re)

/-- [libcrux_iot_ml_kem::ntt::ntt_at_layer_3]:
    Source: 'ml-kem/src/ntt.rs', lines 49:0-59:1 -/
@[reducible]
def ntt.ntt_at_layer_3
  {Vector : Type} (vectortraitsOperationsInst : vector.traits.Operations
  Vector) (zeta_i : Std.Usize) (re : polynomial.PolynomialRingElement Vector)
  (_initial_coefficient_bound : Std.Usize) :
  Result (Std.Usize × (polynomial.PolynomialRingElement Vector))
  := do
  ntt.ntt_at_layer_3_loop vectortraitsOperationsInst
    { start := 0#usize, «end» := 16#usize } zeta_i re

/-- [libcrux_iot_ml_kem::vector::traits::montgomery_multiply_fe]:
    Source: 'ml-kem/src/vector/traits.rs', lines 168:0-170:1
    Visibility: public -/
def vector.traits.montgomery_multiply_fe
  {T : Type} (OperationsInst : vector.traits.Operations T) (v : T)
  (fer : Std.I16) :
  Result T
  := do
  OperationsInst.montgomery_multiply_by_constant v fer

/-- [libcrux_iot_ml_kem::ntt::ntt_layer_int_vec_step]:
    Source: 'ml-kem/src/ntt.rs', lines 63:0-75:1 -/
def ntt.ntt_layer_int_vec_step
  {Vector : Type} (vectortraitsOperationsInst : vector.traits.Operations
  Vector) (coefficients : Array Vector 16#usize) (a : Std.Usize)
  (b : Std.Usize) (scratch : Vector) (zeta_r : Std.I16) :
  Result ((Array Vector 16#usize) × Vector)
  := do
  let scratch1 ← Array.index_usize coefficients b
  let scratch2 ←
    vector.traits.montgomery_multiply_fe vectortraitsOperationsInst scratch1
      zeta_r
  let t ← Array.index_usize coefficients a
  let coefficients1 ← Array.update coefficients b t
  let (t1, index_mut_back) ← Array.index_mut_usize coefficients1 a
  let t2 ← vectortraitsOperationsInst.add t1 scratch2
  let coefficients2 := index_mut_back t2
  let (t3, index_mut_back1) ← Array.index_mut_usize coefficients2 b
  let t4 ← vectortraitsOperationsInst.sub t3 scratch2
  let coefficients3 := index_mut_back1 t4
  ok (coefficients3, scratch2)

/-- [libcrux_iot_ml_kem::ntt::ntt_at_layer_4_plus]: loop body 1:
    Source: 'ml-kem/src/ntt.rs', lines 97:8-106:9 -/
@[rust_loop_body]
def ntt.ntt_at_layer_4_plus_loop0_loop0.body
  {Vector : Type} (vectortraitsOperationsInst : vector.traits.Operations
  Vector) (zeta_i : Std.Usize) (a_offset : Std.Usize) (b_offset : Std.Usize)
  (iter : core_models.ops.range.Range Std.Usize)
  (re : polynomial.PolynomialRingElement Vector) (scratch : Vector) :
  Result (ControlFlow ((core_models.ops.range.Range Std.Usize) ×
    (polynomial.PolynomialRingElement Vector) × Vector)
    ((polynomial.PolynomialRingElement Vector) × Vector))
  := do
  let (o, iter1) ←
    core_models.ops.range.Range.Insts.Core_modelsIterTraitsIteratorIterator.next
      Usize.Insts.Core_modelsIterRangeStep iter
  match o with
  | core_models.option.Option.None => ok (done (re, scratch))
  | core_models.option.Option.Some j =>
    let i ← a_offset + j
    let i1 ← b_offset + j
    let i2 ← polynomial.zeta zeta_i
    let (a, scratch1) ←
      ntt.ntt_layer_int_vec_step vectortraitsOperationsInst re.coefficients i
        i1 scratch i2
    ok (cont (iter1, { coefficients := a }, scratch1))

/-- [libcrux_iot_ml_kem::ntt::ntt_at_layer_4_plus]: loop 1:
    Source: 'ml-kem/src/ntt.rs', lines 97:8-106:9 -/
@[rust_loop]
def ntt.ntt_at_layer_4_plus_loop0_loop0
  {Vector : Type} (vectortraitsOperationsInst : vector.traits.Operations
  Vector) (iter : core_models.ops.range.Range Std.Usize) (zeta_i : Std.Usize)
  (re : polynomial.PolynomialRingElement Vector) (scratch : Vector)
  (a_offset : Std.Usize) (b_offset : Std.Usize) :
  Result ((polynomial.PolynomialRingElement Vector) × Vector)
  := do
  loop
    (fun (iter1, re1, scratch1) => ntt.ntt_at_layer_4_plus_loop0_loop0.body
      vectortraitsOperationsInst zeta_i a_offset b_offset iter1 re1 scratch1)
    (iter, re, scratch)

/-- [libcrux_iot_ml_kem::ntt::ntt_at_layer_4_plus]: loop body 0:
    Source: 'ml-kem/src/ntt.rs', lines 91:4-107:5 -/
@[rust_loop_body]
def ntt.ntt_at_layer_4_plus_loop0.body
  {Vector : Type} (vectortraitsOperationsInst : vector.traits.Operations
  Vector) (step_vec : Std.Usize) (iter : core_models.ops.range.Range Std.Usize)
  (zeta_i : Std.Usize) (re : polynomial.PolynomialRingElement Vector)
  (scratch : Vector) :
  Result (ControlFlow ((core_models.ops.range.Range Std.Usize) × Std.Usize ×
    (polynomial.PolynomialRingElement Vector) × Vector) (Std.Usize ×
    (polynomial.PolynomialRingElement Vector) × Vector))
  := do
  let (o, iter1) ←
    core_models.ops.range.Range.Insts.Core_modelsIterTraitsIteratorIterator.next
      Usize.Insts.Core_modelsIterRangeStep iter
  match o with
  | core_models.option.Option.None => ok (done (zeta_i, re, scratch))
  | core_models.option.Option.Some round =>
    let zeta_i1 ← zeta_i + 1#usize
    let i ← round * 2#usize
    let a_offset ← i * step_vec
    let b_offset ← a_offset + step_vec
    let (re1, scratch1) ←
      ntt.ntt_at_layer_4_plus_loop0_loop0 vectortraitsOperationsInst
        { start := 0#usize, «end» := step_vec } zeta_i1 re scratch a_offset
        b_offset
    ok (cont (iter1, zeta_i1, re1, scratch1))

/-- [libcrux_iot_ml_kem::ntt::ntt_at_layer_4_plus]: loop 0:
    Source: 'ml-kem/src/ntt.rs', lines 91:4-107:5 -/
@[rust_loop]
def ntt.ntt_at_layer_4_plus_loop0
  {Vector : Type} (vectortraitsOperationsInst : vector.traits.Operations
  Vector) (iter : core_models.ops.range.Range Std.Usize) (zeta_i : Std.Usize)
  (re : polynomial.PolynomialRingElement Vector) (scratch : Vector)
  (step_vec : Std.Usize) :
  Result (Std.Usize × (polynomial.PolynomialRingElement Vector) × Vector)
  := do
  loop
    (fun (iter1, zeta_i1, re1, scratch1) => ntt.ntt_at_layer_4_plus_loop0.body
      vectortraitsOperationsInst step_vec iter1 zeta_i1 re1 scratch1)
    (iter, zeta_i, re, scratch)

/-- [libcrux_iot_ml_kem::ntt::ntt_at_layer_4_plus]:
    Source: 'ml-kem/src/ntt.rs', lines 81:0-108:1 -/
def ntt.ntt_at_layer_4_plus
  {Vector : Type} (vectortraitsOperationsInst : vector.traits.Operations
  Vector) (zeta_i : Std.Usize) (re : polynomial.PolynomialRingElement Vector)
  (layer : Std.Usize) (scratch : Vector)
  (_initial_coefficient_bound : Std.Usize) :
  Result (Std.Usize × (polynomial.PolynomialRingElement Vector) × Vector)
  := do
  let step ← 1#usize <<< layer
  let step_vec ← step / 16#usize
  let i ← 128#usize >>> layer
  ntt.ntt_at_layer_4_plus_loop0 vectortraitsOperationsInst
    { start := 0#usize, «end» := i } zeta_i re scratch step_vec

/-- [libcrux_iot_ml_kem::vector::traits::FIELD_ELEMENTS_IN_VECTOR]
    Source: 'ml-kem/src/vector/traits.rs', lines 5:0-5:47
    Visibility: public -/
@[global_simps, irreducible]
def vector.traits.FIELD_ELEMENTS_IN_VECTOR : Std.Usize := 16#usize

/-- [libcrux_iot_ml_kem::polynomial::VECTORS_IN_RING_ELEMENT]
    Source: 'ml-kem/src/polynomial.rs', lines 26:0-27:78 -/
@[global_simps, irreducible]
def polynomial.VECTORS_IN_RING_ELEMENT : Result Std.Usize :=
  constants.COEFFICIENTS_IN_RING_ELEMENT /
    vector.traits.FIELD_ELEMENTS_IN_VECTOR

/-- [libcrux_iot_ml_kem::ntt::ntt_at_layer_7]: loop body 0:
    Source: 'ml-kem/src/ntt.rs', lines 116:4-122:5 -/
@[rust_loop_body]
def ntt.ntt_at_layer_7_loop.body
  {Vector : Type} (vectortraitsOperationsInst : vector.traits.Operations
  Vector) (step : Std.Usize) (iter : core_models.ops.range.Range Std.Usize)
  (re : polynomial.PolynomialRingElement Vector) (scratch : Vector) :
  Result (ControlFlow ((core_models.ops.range.Range Std.Usize) ×
    (polynomial.PolynomialRingElement Vector) × Vector)
    ((polynomial.PolynomialRingElement Vector) × Vector))
  := do
  let (o, iter1) ←
    core_models.ops.range.Range.Insts.Core_modelsIterTraitsIteratorIterator.next
      Usize.Insts.Core_modelsIterRangeStep iter
  match o with
  | core_models.option.Option.None => ok (done (re, scratch))
  | core_models.option.Option.Some j =>
    let i ← j + step
    let scratch1 ← Array.index_usize re.coefficients i
    let scratch2 ←
      vectortraitsOperationsInst.multiply_by_constant scratch1 (-1600)#i16
    let t ← Array.index_usize re.coefficients j
    let a ← Array.update re.coefficients i t
    let (t1, index_mut_back) ← Array.index_mut_usize a j
    let t2 ← vectortraitsOperationsInst.add t1 scratch2
    let a1 := index_mut_back t2
    let (t3, index_mut_back1) ← Array.index_mut_usize a1 i
    let t4 ← vectortraitsOperationsInst.sub t3 scratch2
    let a2 := index_mut_back1 t4
    ok (cont (iter1, { coefficients := a2 }, scratch2))

/-- [libcrux_iot_ml_kem::ntt::ntt_at_layer_7]: loop 0:
    Source: 'ml-kem/src/ntt.rs', lines 116:4-122:5 -/
@[rust_loop]
def ntt.ntt_at_layer_7_loop
  {Vector : Type} (vectortraitsOperationsInst : vector.traits.Operations
  Vector) (iter : core_models.ops.range.Range Std.Usize)
  (re : polynomial.PolynomialRingElement Vector) (scratch : Vector)
  (step : Std.Usize) :
  Result ((polynomial.PolynomialRingElement Vector) × Vector)
  := do
  loop
    (fun (iter1, re1, scratch1) => ntt.ntt_at_layer_7_loop.body
      vectortraitsOperationsInst step iter1 re1 scratch1)
    (iter, re, scratch)

/-- [libcrux_iot_ml_kem::ntt::ntt_at_layer_7]:
    Source: 'ml-kem/src/ntt.rs', lines 111:0-123:1 -/
def ntt.ntt_at_layer_7
  {Vector : Type} (vectortraitsOperationsInst : vector.traits.Operations
  Vector) (re : polynomial.PolynomialRingElement Vector) (scratch : Vector) :
  Result ((polynomial.PolynomialRingElement Vector) × Vector)
  := do
  let i ← polynomial.VECTORS_IN_RING_ELEMENT
  let step ← i / 2#usize
  ntt.ntt_at_layer_7_loop vectortraitsOperationsInst
    { start := 0#usize, «end» := step } re scratch step

/-- [libcrux_iot_ml_kem::polynomial::{libcrux_iot_ml_kem::polynomial::PolynomialRingElement<Vector>}::poly_barrett_reduce]: loop body 0:
    Source: 'ml-kem/src/polynomial.rs', lines 63:8-65:9 -/
@[rust_loop_body]
def polynomial.PolynomialRingElement.poly_barrett_reduce_loop.body
  {Vector : Type} (vectortraitsOperationsInst : vector.traits.Operations
  Vector) (iter : core_models.ops.range.Range Std.Usize)
  (self : polynomial.PolynomialRingElement Vector) :
  Result (ControlFlow ((core_models.ops.range.Range Std.Usize) ×
    (polynomial.PolynomialRingElement Vector))
    (polynomial.PolynomialRingElement Vector))
  := do
  let (o, iter1) ←
    core_models.ops.range.Range.Insts.Core_modelsIterTraitsIteratorIterator.next
      Usize.Insts.Core_modelsIterRangeStep iter
  match o with
  | core_models.option.Option.None => ok (done self)
  | core_models.option.Option.Some i =>
    let (t, index_mut_back) ← Array.index_mut_usize self.coefficients i
    let t1 ← vectortraitsOperationsInst.barrett_reduce t
    let a := index_mut_back t1
    ok (cont (iter1, { coefficients := a }))

/-- [libcrux_iot_ml_kem::polynomial::{libcrux_iot_ml_kem::polynomial::PolynomialRingElement<Vector>}::poly_barrett_reduce]: loop 0:
    Source: 'ml-kem/src/polynomial.rs', lines 63:8-65:9 -/
@[rust_loop]
def polynomial.PolynomialRingElement.poly_barrett_reduce_loop
  {Vector : Type} (vectortraitsOperationsInst : vector.traits.Operations
  Vector) (iter : core_models.ops.range.Range Std.Usize)
  (self : polynomial.PolynomialRingElement Vector) :
  Result (polynomial.PolynomialRingElement Vector)
  := do
  loop
    (fun (iter1, self1) =>
      polynomial.PolynomialRingElement.poly_barrett_reduce_loop.body
      vectortraitsOperationsInst iter1 self1)
    (iter, self)

/-- [libcrux_iot_ml_kem::polynomial::{libcrux_iot_ml_kem::polynomial::PolynomialRingElement<Vector>}::poly_barrett_reduce]:
    Source: 'ml-kem/src/polynomial.rs', lines 62:4-66:5 -/
def polynomial.PolynomialRingElement.poly_barrett_reduce
  {Vector : Type} (vectortraitsOperationsInst : vector.traits.Operations
  Vector) (self : polynomial.PolynomialRingElement Vector) :
  Result (polynomial.PolynomialRingElement Vector)
  := do
  let i ← polynomial.VECTORS_IN_RING_ELEMENT
  polynomial.PolynomialRingElement.poly_barrett_reduce_loop
    vectortraitsOperationsInst { start := 0#usize, «end» := i } self

/-- [libcrux_iot_ml_kem::ntt::ntt_binomially_sampled_ring_element]:
    Source: 'ml-kem/src/ntt.rs', lines 126:0-143:1 -/
def ntt.ntt_binomially_sampled_ring_element
  {Vector : Type} (vectortraitsOperationsInst : vector.traits.Operations
  Vector) (re : polynomial.PolynomialRingElement Vector) (scratch : Vector) :
  Result ((polynomial.PolynomialRingElement Vector) × Vector)
  := do
  let (re1, scratch1) ←
    ntt.ntt_at_layer_7 vectortraitsOperationsInst re scratch
  let (zeta_i, re2, scratch2) ←
    ntt.ntt_at_layer_4_plus vectortraitsOperationsInst 1#usize re1 6#usize
      scratch1 11207#usize
  let i ← 11207#usize + 3328#usize
  let (zeta_i1, re3, scratch3) ←
    ntt.ntt_at_layer_4_plus vectortraitsOperationsInst zeta_i re2 5#usize
      scratch2 i
  let i1 ← 2#usize * 3328#usize
  let i2 ← 11207#usize + i1
  let (zeta_i2, re4, scratch4) ←
    ntt.ntt_at_layer_4_plus vectortraitsOperationsInst zeta_i1 re3 4#usize
      scratch3 i2
  let i3 ← 3#usize * 3328#usize
  let i4 ← 11207#usize + i3
  let (zeta_i3, re5) ←
    ntt.ntt_at_layer_3 vectortraitsOperationsInst zeta_i2 re4 i4
  let i5 ← 4#usize * 3328#usize
  let i6 ← 11207#usize + i5
  let (zeta_i4, re6) ←
    ntt.ntt_at_layer_2 vectortraitsOperationsInst zeta_i3 re5 i6
  let i7 ← 5#usize * 3328#usize
  let i8 ← 11207#usize + i7
  let (_, re7) ← ntt.ntt_at_layer_1 vectortraitsOperationsInst zeta_i4 re6 i8
  let re8 ←
    polynomial.PolynomialRingElement.poly_barrett_reduce
      vectortraitsOperationsInst re7
  ok (re8, scratch4)

/-- [libcrux_iot_ml_kem::ntt::ntt_vector_u]:
    Source: 'ml-kem/src/ntt.rs', lines 146:0-165:1 -/
def ntt.ntt_vector_u
  {Vector : Type} (VECTOR_U_COMPRESSION_FACTOR : Std.Usize)
  (vectortraitsOperationsInst : vector.traits.Operations Vector)
  (re : polynomial.PolynomialRingElement Vector) (scratch : Vector) :
  Result ((polynomial.PolynomialRingElement Vector) × Vector)
  := do
  let (zeta_i, re1, scratch1) ←
    ntt.ntt_at_layer_4_plus vectortraitsOperationsInst 0#usize re 7#usize
      scratch 3328#usize
  let i ← 2#usize * 3328#usize
  let (zeta_i1, re2, scratch2) ←
    ntt.ntt_at_layer_4_plus vectortraitsOperationsInst zeta_i re1 6#usize
      scratch1 i
  let i1 ← 3#usize * 3328#usize
  let (zeta_i2, re3, scratch3) ←
    ntt.ntt_at_layer_4_plus vectortraitsOperationsInst zeta_i1 re2 5#usize
      scratch2 i1
  let i2 ← 4#usize * 3328#usize
  let (zeta_i3, re4, scratch4) ←
    ntt.ntt_at_layer_4_plus vectortraitsOperationsInst zeta_i2 re3 4#usize
      scratch3 i2
  let i3 ← 5#usize * 3328#usize
  let (zeta_i4, re5) ←
    ntt.ntt_at_layer_3 vectortraitsOperationsInst zeta_i3 re4 i3
  let i4 ← 6#usize * 3328#usize
  let (zeta_i5, re6) ←
    ntt.ntt_at_layer_2 vectortraitsOperationsInst zeta_i4 re5 i4
  let i5 ← 7#usize * 3328#usize
  let (_, re7) ← ntt.ntt_at_layer_1 vectortraitsOperationsInst zeta_i5 re6 i5
  let re8 ←
    polynomial.PolynomialRingElement.poly_barrett_reduce
      vectortraitsOperationsInst re7
  ok (re8, scratch4)

/-- [libcrux_iot_ml_kem::vector::portable::arithmetic::MONTGOMERY_SHIFT]
    Source: 'ml-kem/src/vector/portable/arithmetic.rs', lines 18:0-18:43 -/
@[global_simps, irreducible]
def vector.portable.arithmetic.MONTGOMERY_SHIFT : Std.U8 := 16#u8

/-- [libcrux_iot_ml_kem::vector::portable::arithmetic::BARRETT_MULTIPLIER]
    Source: 'ml-kem/src/vector/portable/arithmetic.rs', lines 24:0-24:49 -/
@[global_simps, irreducible]
def vector.portable.arithmetic.BARRETT_MULTIPLIER : Std.I32 := 20159#i32

/-- [libcrux_iot_ml_kem::vector::traits::BARRETT_SHIFT]
    Source: 'ml-kem/src/vector/traits.rs', lines 7:0-7:34
    Visibility: public -/
@[global_simps, irreducible]
def vector.traits.BARRETT_SHIFT : Std.I32 := 26#i32

/-- [libcrux_iot_ml_kem::vector::traits::BARRETT_R]
    Source: 'ml-kem/src/vector/traits.rs', lines 8:0-8:46
    Visibility: public -/
@[global_simps, irreducible]
def vector.traits.BARRETT_R : Result Std.I32 :=
  1#i32 <<< vector.traits.BARRETT_SHIFT

/-- [libcrux_iot_ml_kem::vector::traits::FIELD_MODULUS]
    Source: 'ml-kem/src/vector/traits.rs', lines 4:0-4:36
    Visibility: public -/
@[global_simps, irreducible]
def vector.traits.FIELD_MODULUS : Std.I16 := 3329#i16

/-- [libcrux_iot_ml_kem::vector::portable::arithmetic::barrett_reduce_element]:
    Source: 'ml-kem/src/vector/portable/arithmetic.rs', lines 124:0-131:1 -/
def vector.portable.arithmetic.barrett_reduce_element
  (value : Std.I16) : Result Std.I16 := do
  let i ← I16.Insts.Libcrux_secretsIntCastOps.as_i32 value
  let i1 ←
    core_models.num.I32.wrapping_mul i
      vector.portable.arithmetic.BARRETT_MULTIPLIER
  let i2 ← vector.traits.BARRETT_R
  let i3 ← i2 >>> 1#i32
  let t ← core_models.num.I32.wrapping_add i1 i3
  let i4 ← lift (IScalar.hcast .U32 vector.traits.BARRETT_SHIFT)
  let i5 ← t >>> i4
  let quotient ← I32.Insts.Libcrux_secretsIntCastOps.as_i16 i5
  let i6 ←
    core_models.num.I16.wrapping_mul quotient vector.traits.FIELD_MODULUS
  core_models.num.I16.wrapping_sub value i6

/-- [libcrux_iot_ml_kem::vector::traits::INVERSE_OF_MODULUS_MOD_MONTGOMERY_R]
    Source: 'ml-kem/src/vector/traits.rs', lines 6:0-6:59
    Visibility: public -/
@[global_simps, irreducible]
def vector.traits.INVERSE_OF_MODULUS_MOD_MONTGOMERY_R : Std.U32 := 62209#u32

/-- [libcrux_iot_ml_kem::vector::portable::arithmetic::montgomery_reduce_element]:
    Source: 'ml-kem/src/vector/portable/arithmetic.rs', lines 156:0-170:1 -/
def vector.portable.arithmetic.montgomery_reduce_element
  (value : Std.I32) : Result Std.I16 := do
  let i ← I32.Insts.Libcrux_secretsIntCastOps.as_i16 value
  let i1 ← I16.Insts.Libcrux_secretsIntCastOps.as_i32 i
  let i2 ←
    libcrux_secrets.traits.Classify.Blanket.classify
      vector.traits.INVERSE_OF_MODULUS_MOD_MONTGOMERY_R
  let i3 ← U32.Insts.Libcrux_secretsIntCastOps.as_i32 i2
  let k ← core_models.num.I32.wrapping_mul i1 i3
  let i4 ← I32.Insts.Libcrux_secretsIntCastOps.as_i16 k
  let i5 ← I16.Insts.Libcrux_secretsIntCastOps.as_i32 i4
  let i6 ←
    libcrux_secrets.traits.Classify.Blanket.classify
      vector.traits.FIELD_MODULUS
  let i7 ← I16.Insts.Libcrux_secretsIntCastOps.as_i32 i6
  let k_times_modulus ← core_models.num.I32.wrapping_mul i5 i7
  let i8 ←
    lift (UScalar.cast .U32 vector.portable.arithmetic.MONTGOMERY_SHIFT)
  let i9 ← k_times_modulus >>> i8
  let c ← I32.Insts.Libcrux_secretsIntCastOps.as_i16 i9
  let i10 ←
    lift (UScalar.cast .U32 vector.portable.arithmetic.MONTGOMERY_SHIFT)
  let i11 ← value >>> i10
  let value_high ← I32.Insts.Libcrux_secretsIntCastOps.as_i16 i11
  core_models.num.I16.wrapping_sub value_high c

/-- [libcrux_iot_ml_kem::vector::portable::arithmetic::montgomery_multiply_fe_by_fer]:
    Source: 'ml-kem/src/vector/portable/arithmetic.rs', lines 181:0-187:1 -/
def vector.portable.arithmetic.montgomery_multiply_fe_by_fer
  (fe : Std.I16) (fer : Std.I16) : Result Std.I16 := do
  let i ← I16.Insts.Libcrux_secretsIntCastOps.as_i32 fe
  let i1 ← I16.Insts.Libcrux_secretsIntCastOps.as_i32 fer
  let product ← core_models.num.I32.wrapping_mul i i1
  vector.portable.arithmetic.montgomery_reduce_element product

/-- [libcrux_iot_ml_kem::vector::portable::vector_type::PortableVector]
    Source: 'ml-kem/src/vector/portable/vector_type.rs', lines 9:0-11:1
    Visibility: public -/
structure vector.portable.vector_type.PortableVector where
  elements : Array Std.I16 16#usize

/-- [libcrux_iot_ml_kem::vector::portable::ntt::ntt_step]:
    Source: 'ml-kem/src/vector/portable/ntt.rs', lines 7:0-15:1 -/
def vector.portable.ntt.ntt_step
  (vec : vector.portable.vector_type.PortableVector) (zeta : Std.I16)
  (i : Std.Usize) (j : Std.Usize) :
  Result vector.portable.vector_type.PortableVector
  := do
  let i1 ← Array.index_usize vec.elements j
  let i2 ← libcrux_secrets.traits.Classify.Blanket.classify zeta
  let t ← vector.portable.arithmetic.montgomery_multiply_fe_by_fer i1 i2
  let i3 ← Array.index_usize vec.elements i
  let a_minus_t ← core_models.num.I16.wrapping_sub i3 t
  let a_plus_t ← core_models.num.I16.wrapping_add i3 t
  let a ← Array.update vec.elements j a_minus_t
  let a1 ← Array.update a i a_plus_t
  ok { elements := a1 }

/-- [libcrux_iot_ml_kem::vector::portable::ntt::ntt_layer_1_step]:
    Source: 'ml-kem/src/vector/portable/ntt.rs', lines 18:0-33:1 -/
def vector.portable.ntt.ntt_layer_1_step
  (vec : vector.portable.vector_type.PortableVector) (zeta0 : Std.I16)
  (zeta1 : Std.I16) (zeta2 : Std.I16) (zeta3 : Std.I16) :
  Result vector.portable.vector_type.PortableVector
  := do
  let vec1 ← vector.portable.ntt.ntt_step vec zeta0 0#usize 2#usize
  let vec2 ← vector.portable.ntt.ntt_step vec1 zeta0 1#usize 3#usize
  let vec3 ← vector.portable.ntt.ntt_step vec2 zeta1 4#usize 6#usize
  let vec4 ← vector.portable.ntt.ntt_step vec3 zeta1 5#usize 7#usize
  let vec5 ← vector.portable.ntt.ntt_step vec4 zeta2 8#usize 10#usize
  let vec6 ← vector.portable.ntt.ntt_step vec5 zeta2 9#usize 11#usize
  let vec7 ← vector.portable.ntt.ntt_step vec6 zeta3 12#usize 14#usize
  vector.portable.ntt.ntt_step vec7 zeta3 13#usize 15#usize

/-- [libcrux_iot_ml_kem::vector::portable::ntt::ntt_layer_2_step]:
    Source: 'ml-kem/src/vector/portable/ntt.rs', lines 36:0-45:1 -/
def vector.portable.ntt.ntt_layer_2_step
  (vec : vector.portable.vector_type.PortableVector) (zeta0 : Std.I16)
  (zeta1 : Std.I16) :
  Result vector.portable.vector_type.PortableVector
  := do
  let vec1 ← vector.portable.ntt.ntt_step vec zeta0 0#usize 4#usize
  let vec2 ← vector.portable.ntt.ntt_step vec1 zeta0 1#usize 5#usize
  let vec3 ← vector.portable.ntt.ntt_step vec2 zeta0 2#usize 6#usize
  let vec4 ← vector.portable.ntt.ntt_step vec3 zeta0 3#usize 7#usize
  let vec5 ← vector.portable.ntt.ntt_step vec4 zeta1 8#usize 12#usize
  let vec6 ← vector.portable.ntt.ntt_step vec5 zeta1 9#usize 13#usize
  let vec7 ← vector.portable.ntt.ntt_step vec6 zeta1 10#usize 14#usize
  vector.portable.ntt.ntt_step vec7 zeta1 11#usize 15#usize

/-- [libcrux_iot_ml_kem::vector::portable::ntt::ntt_layer_3_step]:
    Source: 'ml-kem/src/vector/portable/ntt.rs', lines 48:0-57:1 -/
def vector.portable.ntt.ntt_layer_3_step
  (vec : vector.portable.vector_type.PortableVector) (zeta : Std.I16) :
  Result vector.portable.vector_type.PortableVector
  := do
  let vec1 ← vector.portable.ntt.ntt_step vec zeta 0#usize 8#usize
  let vec2 ← vector.portable.ntt.ntt_step vec1 zeta 1#usize 9#usize
  let vec3 ← vector.portable.ntt.ntt_step vec2 zeta 2#usize 10#usize
  let vec4 ← vector.portable.ntt.ntt_step vec3 zeta 3#usize 11#usize
  let vec5 ← vector.portable.ntt.ntt_step vec4 zeta 4#usize 12#usize
  let vec6 ← vector.portable.ntt.ntt_step vec5 zeta 5#usize 13#usize
  let vec7 ← vector.portable.ntt.ntt_step vec6 zeta 6#usize 14#usize
  vector.portable.ntt.ntt_step vec7 zeta 7#usize 15#usize

/-- [libcrux_iot_ml_kem::vector::portable::ntt::inv_ntt_step]:
    Source: 'ml-kem/src/vector/portable/ntt.rs', lines 61:0-70:1 -/
def vector.portable.ntt.inv_ntt_step
  (vec : vector.portable.vector_type.PortableVector) (zeta : Std.I16)
  (i : Std.Usize) (j : Std.Usize) :
  Result vector.portable.vector_type.PortableVector
  := do
  let i1 ← Array.index_usize vec.elements j
  let i2 ← Array.index_usize vec.elements i
  let a_minus_b ← core_models.num.I16.wrapping_sub i1 i2
  let a_plus_b ← core_models.num.I16.wrapping_add i1 i2
  let o0 ← vector.portable.arithmetic.barrett_reduce_element a_plus_b
  let i3 ← libcrux_secrets.traits.Classify.Blanket.classify zeta
  let o1 ←
    vector.portable.arithmetic.montgomery_multiply_fe_by_fer a_minus_b i3
  let a ← Array.update vec.elements i o0
  let a1 ← Array.update a j o1
  ok { elements := a1 }

/-- [libcrux_iot_ml_kem::vector::portable::ntt::inv_ntt_layer_1_step]:
    Source: 'ml-kem/src/vector/portable/ntt.rs', lines 73:0-88:1 -/
def vector.portable.ntt.inv_ntt_layer_1_step
  (vec : vector.portable.vector_type.PortableVector) (zeta0 : Std.I16)
  (zeta1 : Std.I16) (zeta2 : Std.I16) (zeta3 : Std.I16) :
  Result vector.portable.vector_type.PortableVector
  := do
  let vec1 ← vector.portable.ntt.inv_ntt_step vec zeta0 0#usize 2#usize
  let vec2 ← vector.portable.ntt.inv_ntt_step vec1 zeta0 1#usize 3#usize
  let vec3 ← vector.portable.ntt.inv_ntt_step vec2 zeta1 4#usize 6#usize
  let vec4 ← vector.portable.ntt.inv_ntt_step vec3 zeta1 5#usize 7#usize
  let vec5 ← vector.portable.ntt.inv_ntt_step vec4 zeta2 8#usize 10#usize
  let vec6 ← vector.portable.ntt.inv_ntt_step vec5 zeta2 9#usize 11#usize
  let vec7 ← vector.portable.ntt.inv_ntt_step vec6 zeta3 12#usize 14#usize
  vector.portable.ntt.inv_ntt_step vec7 zeta3 13#usize 15#usize

/-- [libcrux_iot_ml_kem::vector::portable::ntt::inv_ntt_layer_2_step]:
    Source: 'ml-kem/src/vector/portable/ntt.rs', lines 91:0-100:1 -/
def vector.portable.ntt.inv_ntt_layer_2_step
  (vec : vector.portable.vector_type.PortableVector) (zeta0 : Std.I16)
  (zeta1 : Std.I16) :
  Result vector.portable.vector_type.PortableVector
  := do
  let vec1 ← vector.portable.ntt.inv_ntt_step vec zeta0 0#usize 4#usize
  let vec2 ← vector.portable.ntt.inv_ntt_step vec1 zeta0 1#usize 5#usize
  let vec3 ← vector.portable.ntt.inv_ntt_step vec2 zeta0 2#usize 6#usize
  let vec4 ← vector.portable.ntt.inv_ntt_step vec3 zeta0 3#usize 7#usize
  let vec5 ← vector.portable.ntt.inv_ntt_step vec4 zeta1 8#usize 12#usize
  let vec6 ← vector.portable.ntt.inv_ntt_step vec5 zeta1 9#usize 13#usize
  let vec7 ← vector.portable.ntt.inv_ntt_step vec6 zeta1 10#usize 14#usize
  vector.portable.ntt.inv_ntt_step vec7 zeta1 11#usize 15#usize

/-- [libcrux_iot_ml_kem::vector::portable::ntt::inv_ntt_layer_3_step]:
    Source: 'ml-kem/src/vector/portable/ntt.rs', lines 103:0-112:1 -/
def vector.portable.ntt.inv_ntt_layer_3_step
  (vec : vector.portable.vector_type.PortableVector) (zeta : Std.I16) :
  Result vector.portable.vector_type.PortableVector
  := do
  let vec1 ← vector.portable.ntt.inv_ntt_step vec zeta 0#usize 8#usize
  let vec2 ← vector.portable.ntt.inv_ntt_step vec1 zeta 1#usize 9#usize
  let vec3 ← vector.portable.ntt.inv_ntt_step vec2 zeta 2#usize 10#usize
  let vec4 ← vector.portable.ntt.inv_ntt_step vec3 zeta 3#usize 11#usize
  let vec5 ← vector.portable.ntt.inv_ntt_step vec4 zeta 4#usize 12#usize
  let vec6 ← vector.portable.ntt.inv_ntt_step vec5 zeta 5#usize 13#usize
  let vec7 ← vector.portable.ntt.inv_ntt_step vec6 zeta 6#usize 14#usize
  vector.portable.ntt.inv_ntt_step vec7 zeta 7#usize 15#usize

/-- [libcrux_iot_ml_kem::vector::portable::ntt::accumulating_ntt_multiply_binomials_fill_cache]:
    Source: 'ml-kem/src/vector/portable/ntt.rs', lines 137:0-165:1 -/
def vector.portable.ntt.accumulating_ntt_multiply_binomials_fill_cache
  (a : vector.portable.vector_type.PortableVector)
  (b : vector.portable.vector_type.PortableVector) (zeta : Std.I16)
  (i : Std.Usize) (out : Slice Std.I32)
  (cache : vector.portable.vector_type.PortableVector) :
  Result ((Slice Std.I32) × vector.portable.vector_type.PortableVector)
  := do
  let i1 ← 2#usize * i
  let ai ← Array.index_usize a.elements i1
  let bi ← Array.index_usize b.elements i1
  let i2 ← i1 + 1#usize
  let aj ← Array.index_usize a.elements i2
  let i3 ← i1 + 1#usize
  let bj ← Array.index_usize b.elements i3
  let i4 ← I16.Insts.Libcrux_secretsIntCastOps.as_i32 ai
  let i5 ← I16.Insts.Libcrux_secretsIntCastOps.as_i32 bi
  let ai_bi ← core_models.num.I32.wrapping_mul i4 i5
  let i6 ← I16.Insts.Libcrux_secretsIntCastOps.as_i32 bj
  let i7 ← I16.Insts.Libcrux_secretsIntCastOps.as_i32 zeta
  let bj_zeta_ ← core_models.num.I32.wrapping_mul i6 i7
  let bj_zeta ← vector.portable.arithmetic.montgomery_reduce_element bj_zeta_
  let a1 ← Array.update cache.elements i bj_zeta
  let i8 ← I16.Insts.Libcrux_secretsIntCastOps.as_i32 aj
  let i9 ← I16.Insts.Libcrux_secretsIntCastOps.as_i32 bj_zeta
  let aj_bj_zeta ← core_models.num.I32.wrapping_mul i8 i9
  let ai_bi_aj_bj ← core_models.num.I32.wrapping_add ai_bi aj_bj_zeta
  let ai_bj ← core_models.num.I32.wrapping_mul i4 i6
  let aj_bi ← core_models.num.I32.wrapping_mul i8 i5
  let ai_bj_aj_bi ← core_models.num.I32.wrapping_add ai_bj aj_bi
  let i10 ← Slice.index_usize out i1
  let i11 ← core_models.num.I32.wrapping_add i10 ai_bi_aj_bj
  let out1 ← Slice.update out i1 i11
  let i12 ← i1 + 1#usize
  let i13 ← Slice.index_usize out1 i12
  let i14 ← core_models.num.I32.wrapping_add i13 ai_bj_aj_bi
  let i15 ← i1 + 1#usize
  let out2 ← Slice.update out1 i15 i14
  ok (out2, { elements := a1 })

/-- [libcrux_iot_ml_kem::vector::portable::ntt::accumulating_ntt_multiply_binomials_use_cache]:
    Source: 'ml-kem/src/vector/portable/ntt.rs', lines 170:0-194:1 -/
def vector.portable.ntt.accumulating_ntt_multiply_binomials_use_cache
  (a : vector.portable.vector_type.PortableVector)
  (b : vector.portable.vector_type.PortableVector) (i : Std.Usize)
  (out : Slice Std.I32) (cache : vector.portable.vector_type.PortableVector) :
  Result (Slice Std.I32)
  := do
  let i1 ← 2#usize * i
  let ai ← Array.index_usize a.elements i1
  let bi ← Array.index_usize b.elements i1
  let i2 ← i1 + 1#usize
  let aj ← Array.index_usize a.elements i2
  let i3 ← i1 + 1#usize
  let bj ← Array.index_usize b.elements i3
  let i4 ← I16.Insts.Libcrux_secretsIntCastOps.as_i32 ai
  let i5 ← I16.Insts.Libcrux_secretsIntCastOps.as_i32 bi
  let ai_bi ← core_models.num.I32.wrapping_mul i4 i5
  let i6 ← I16.Insts.Libcrux_secretsIntCastOps.as_i32 aj
  let i7 ← Array.index_usize cache.elements i
  let i8 ← I16.Insts.Libcrux_secretsIntCastOps.as_i32 i7
  let aj_bj_zeta ← core_models.num.I32.wrapping_mul i6 i8
  let ai_bi_aj_bj ← core_models.num.I32.wrapping_add ai_bi aj_bj_zeta
  let i9 ← I16.Insts.Libcrux_secretsIntCastOps.as_i32 bj
  let ai_bj ← core_models.num.I32.wrapping_mul i4 i9
  let aj_bi ← core_models.num.I32.wrapping_mul i6 i5
  let ai_bj_aj_bi ← core_models.num.I32.wrapping_add ai_bj aj_bi
  let i10 ← Slice.index_usize out i1
  let i11 ← core_models.num.I32.wrapping_add i10 ai_bi_aj_bj
  let out1 ← Slice.update out i1 i11
  let i12 ← i1 + 1#usize
  let i13 ← Slice.index_usize out1 i12
  let i14 ← core_models.num.I32.wrapping_add i13 ai_bj_aj_bi
  let i15 ← i1 + 1#usize
  Slice.update out1 i15 i14

/-- [libcrux_iot_ml_kem::vector::portable::ntt::accumulating_ntt_multiply_binomials]:
    Source: 'ml-kem/src/vector/portable/ntt.rs', lines 199:0-225:1 -/
def vector.portable.ntt.accumulating_ntt_multiply_binomials
  (a : vector.portable.vector_type.PortableVector)
  (b : vector.portable.vector_type.PortableVector) (zeta : Std.I16)
  (i : Std.Usize) (out : Slice Std.I32) :
  Result (Slice Std.I32)
  := do
  let i1 ← 2#usize * i
  let ai ← Array.index_usize a.elements i1
  let bi ← Array.index_usize b.elements i1
  let i2 ← i1 + 1#usize
  let aj ← Array.index_usize a.elements i2
  let i3 ← i1 + 1#usize
  let bj ← Array.index_usize b.elements i3
  let i4 ← I16.Insts.Libcrux_secretsIntCastOps.as_i32 ai
  let i5 ← I16.Insts.Libcrux_secretsIntCastOps.as_i32 bi
  let ai_bi ← core_models.num.I32.wrapping_mul i4 i5
  let i6 ← I16.Insts.Libcrux_secretsIntCastOps.as_i32 bj
  let i7 ← I16.Insts.Libcrux_secretsIntCastOps.as_i32 zeta
  let bj_zeta_ ← core_models.num.I32.wrapping_mul i6 i7
  let bj_zeta ← vector.portable.arithmetic.montgomery_reduce_element bj_zeta_
  let i8 ← I16.Insts.Libcrux_secretsIntCastOps.as_i32 aj
  let i9 ← I16.Insts.Libcrux_secretsIntCastOps.as_i32 bj_zeta
  let aj_bj_zeta ← core_models.num.I32.wrapping_mul i8 i9
  let ai_bi_aj_bj ← core_models.num.I32.wrapping_add ai_bi aj_bj_zeta
  let ai_bj ← core_models.num.I32.wrapping_mul i4 i6
  let aj_bi ← core_models.num.I32.wrapping_mul i8 i5
  let ai_bj_aj_bi ← core_models.num.I32.wrapping_add ai_bj aj_bi
  let i10 ← Slice.index_usize out i1
  let i11 ← core_models.num.I32.wrapping_add i10 ai_bi_aj_bj
  let out1 ← Slice.update out i1 i11
  let i12 ← i1 + 1#usize
  let i13 ← Slice.index_usize out1 i12
  let i14 ← core_models.num.I32.wrapping_add i13 ai_bj_aj_bi
  let i15 ← i1 + 1#usize
  Slice.update out1 i15 i14

/-- [libcrux_iot_ml_kem::vector::portable::ntt::accumulating_ntt_multiply]:
    Source: 'ml-kem/src/vector/portable/ntt.rs', lines 230:0-251:1 -/
def vector.portable.ntt.accumulating_ntt_multiply
  (lhs : vector.portable.vector_type.PortableVector)
  (rhs : vector.portable.vector_type.PortableVector) (out : Slice Std.I32)
  (zeta0 : Std.I16) (zeta1 : Std.I16) (zeta2 : Std.I16) (zeta3 : Std.I16) :
  Result (Slice Std.I32)
  := do
  let nzeta0 ← core_models.num.I16.wrapping_neg zeta0
  let nzeta1 ← core_models.num.I16.wrapping_neg zeta1
  let nzeta2 ← core_models.num.I16.wrapping_neg zeta2
  let nzeta3 ← core_models.num.I16.wrapping_neg zeta3
  let i ← libcrux_secrets.traits.Classify.Blanket.classify zeta0
  let out1 ←
    vector.portable.ntt.accumulating_ntt_multiply_binomials lhs rhs i 0#usize
      out
  let i1 ← libcrux_secrets.traits.Classify.Blanket.classify nzeta0
  let out2 ←
    vector.portable.ntt.accumulating_ntt_multiply_binomials lhs rhs i1 1#usize
      out1
  let i2 ← libcrux_secrets.traits.Classify.Blanket.classify zeta1
  let out3 ←
    vector.portable.ntt.accumulating_ntt_multiply_binomials lhs rhs i2 2#usize
      out2
  let i3 ← libcrux_secrets.traits.Classify.Blanket.classify nzeta1
  let out4 ←
    vector.portable.ntt.accumulating_ntt_multiply_binomials lhs rhs i3 3#usize
      out3
  let i4 ← libcrux_secrets.traits.Classify.Blanket.classify zeta2
  let out5 ←
    vector.portable.ntt.accumulating_ntt_multiply_binomials lhs rhs i4 4#usize
      out4
  let i5 ← libcrux_secrets.traits.Classify.Blanket.classify nzeta2
  let out6 ←
    vector.portable.ntt.accumulating_ntt_multiply_binomials lhs rhs i5 5#usize
      out5
  let i6 ← libcrux_secrets.traits.Classify.Blanket.classify zeta3
  let out7 ←
    vector.portable.ntt.accumulating_ntt_multiply_binomials lhs rhs i6 6#usize
      out6
  let i7 ← libcrux_secrets.traits.Classify.Blanket.classify nzeta3
  vector.portable.ntt.accumulating_ntt_multiply_binomials lhs rhs i7 7#usize
    out7

/-- [libcrux_iot_ml_kem::vector::portable::ntt::accumulating_ntt_multiply_fill_cache]:
    Source: 'ml-kem/src/vector/portable/ntt.rs', lines 256:0-278:1 -/
def vector.portable.ntt.accumulating_ntt_multiply_fill_cache
  (lhs : vector.portable.vector_type.PortableVector)
  (rhs : vector.portable.vector_type.PortableVector) (out : Slice Std.I32)
  (cache : vector.portable.vector_type.PortableVector) (zeta0 : Std.I16)
  (zeta1 : Std.I16) (zeta2 : Std.I16) (zeta3 : Std.I16) :
  Result ((Slice Std.I32) × vector.portable.vector_type.PortableVector)
  := do
  let nzeta0 ← core_models.num.I16.wrapping_neg zeta0
  let nzeta1 ← core_models.num.I16.wrapping_neg zeta1
  let nzeta2 ← core_models.num.I16.wrapping_neg zeta2
  let nzeta3 ← core_models.num.I16.wrapping_neg zeta3
  let i ← libcrux_secrets.traits.Classify.Blanket.classify zeta0
  let (out1, cache1) ←
    vector.portable.ntt.accumulating_ntt_multiply_binomials_fill_cache lhs rhs
      i 0#usize out cache
  let i1 ← libcrux_secrets.traits.Classify.Blanket.classify nzeta0
  let (out2, cache2) ←
    vector.portable.ntt.accumulating_ntt_multiply_binomials_fill_cache lhs rhs
      i1 1#usize out1 cache1
  let i2 ← libcrux_secrets.traits.Classify.Blanket.classify zeta1
  let (out3, cache3) ←
    vector.portable.ntt.accumulating_ntt_multiply_binomials_fill_cache lhs rhs
      i2 2#usize out2 cache2
  let i3 ← libcrux_secrets.traits.Classify.Blanket.classify nzeta1
  let (out4, cache4) ←
    vector.portable.ntt.accumulating_ntt_multiply_binomials_fill_cache lhs rhs
      i3 3#usize out3 cache3
  let i4 ← libcrux_secrets.traits.Classify.Blanket.classify zeta2
  let (out5, cache5) ←
    vector.portable.ntt.accumulating_ntt_multiply_binomials_fill_cache lhs rhs
      i4 4#usize out4 cache4
  let i5 ← libcrux_secrets.traits.Classify.Blanket.classify nzeta2
  let (out6, cache6) ←
    vector.portable.ntt.accumulating_ntt_multiply_binomials_fill_cache lhs rhs
      i5 5#usize out5 cache5
  let i6 ← libcrux_secrets.traits.Classify.Blanket.classify zeta3
  let (out7, cache7) ←
    vector.portable.ntt.accumulating_ntt_multiply_binomials_fill_cache lhs rhs
      i6 6#usize out6 cache6
  let i7 ← libcrux_secrets.traits.Classify.Blanket.classify nzeta3
  vector.portable.ntt.accumulating_ntt_multiply_binomials_fill_cache lhs rhs i7
    7#usize out7 cache7

/-- [libcrux_iot_ml_kem::vector::portable::ntt::accumulating_ntt_multiply_use_cache]:
    Source: 'ml-kem/src/vector/portable/ntt.rs', lines 283:0-297:1 -/
def vector.portable.ntt.accumulating_ntt_multiply_use_cache
  (lhs : vector.portable.vector_type.PortableVector)
  (rhs : vector.portable.vector_type.PortableVector) (out : Slice Std.I32)
  (cache : vector.portable.vector_type.PortableVector) :
  Result (Slice Std.I32)
  := do
  let out1 ←
    vector.portable.ntt.accumulating_ntt_multiply_binomials_use_cache lhs rhs
      0#usize out cache
  let out2 ←
    vector.portable.ntt.accumulating_ntt_multiply_binomials_use_cache lhs rhs
      1#usize out1 cache
  let out3 ←
    vector.portable.ntt.accumulating_ntt_multiply_binomials_use_cache lhs rhs
      2#usize out2 cache
  let out4 ←
    vector.portable.ntt.accumulating_ntt_multiply_binomials_use_cache lhs rhs
      3#usize out3 cache
  let out5 ←
    vector.portable.ntt.accumulating_ntt_multiply_binomials_use_cache lhs rhs
      4#usize out4 cache
  let out6 ←
    vector.portable.ntt.accumulating_ntt_multiply_binomials_use_cache lhs rhs
      5#usize out5 cache
  let out7 ←
    vector.portable.ntt.accumulating_ntt_multiply_binomials_use_cache lhs rhs
      6#usize out6 cache
  vector.portable.ntt.accumulating_ntt_multiply_binomials_use_cache lhs rhs
    7#usize out7 cache

end libcrux_iot_ml_kem
