-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [libcrux_iot_ml_dsa]
import Aeneas
import CoreModels
open core_models
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace libcrux_iot_ml_dsa

/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::MONTGOMERY_SHIFT]
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 11:0-11:43 -/
@[global_simps, irreducible]
def simd.portable.arithmetic.MONTGOMERY_SHIFT : Std.U8 := 32#u8

/-- [libcrux_iot_ml_dsa::simd::portable::vector_type::Coefficients]
    Source: 'ml-dsa/src/simd/portable/vector_type.rs', lines 10:0-12:1 -/
structure simd.portable.vector_type.Coefficients where
  values : Array Std.I32 8#usize

/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::add]: loop body 0:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 15:4-17:5
    Visibility: public -/
@[rust_loop_body]
def simd.portable.arithmetic.add_loop.body
  (rhs : simd.portable.vector_type.Coefficients)
  (iter : core_models.ops.range.Range Std.Usize) (a : Array Std.I32 8#usize) :
  Result (ControlFlow ((core_models.ops.range.Range Std.Usize) × (Array
    Std.I32 8#usize)) (Array Std.I32 8#usize))
  := do
  let (o, iter1) ←
    core_models.ops.range.Range.Insts.Core_modelsIterTraitsIteratorIterator.next
      Usize.Insts.Core_modelsIterRangeStep iter
  match o with
  | core_models.option.Option.None => ok (done a)
  | core_models.option.Option.Some i =>
    let i1 ← Array.index_usize rhs.values i
    let i2 ← Array.index_usize a i
    let i3 ← i2 + i1
    let a1 ← Array.update a i i3
    ok (cont (iter1, a1))

/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::add]: loop 0:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 15:4-17:5
    Visibility: public -/
@[rust_loop]
def simd.portable.arithmetic.add_loop
  (iter : core_models.ops.range.Range Std.Usize) (a : Array Std.I32 8#usize)
  (rhs : simd.portable.vector_type.Coefficients) :
  Result (Array Std.I32 8#usize)
  := do
  loop
    (fun (iter1, a1) => simd.portable.arithmetic.add_loop.body rhs iter1 a1)
    (iter, a)

/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::add]:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 14:0-21:1
    Visibility: public -/
def simd.portable.arithmetic.add
  (lhs : simd.portable.vector_type.Coefficients)
  (rhs : simd.portable.vector_type.Coefficients) :
  Result simd.portable.vector_type.Coefficients
  := do
  let s ← lift (Array.to_slice lhs.values)
  let i ← core_models.slice.Slice.len s
  let a ←
    simd.portable.arithmetic.add_loop { start := 0#usize, «end» := i }
      lhs.values rhs
  ok { values := a }

/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::subtract]: loop body 0:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 25:4-27:5
    Visibility: public -/
@[rust_loop_body]
def simd.portable.arithmetic.subtract_loop.body
  (rhs : simd.portable.vector_type.Coefficients)
  (iter : core_models.ops.range.Range Std.Usize) (a : Array Std.I32 8#usize) :
  Result (ControlFlow ((core_models.ops.range.Range Std.Usize) × (Array
    Std.I32 8#usize)) (Array Std.I32 8#usize))
  := do
  let (o, iter1) ←
    core_models.ops.range.Range.Insts.Core_modelsIterTraitsIteratorIterator.next
      Usize.Insts.Core_modelsIterRangeStep iter
  match o with
  | core_models.option.Option.None => ok (done a)
  | core_models.option.Option.Some i =>
    let i1 ← Array.index_usize rhs.values i
    let i2 ← Array.index_usize a i
    let i3 ← i2 - i1
    let a1 ← Array.update a i i3
    ok (cont (iter1, a1))

/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::subtract]: loop 0:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 25:4-27:5
    Visibility: public -/
@[rust_loop]
def simd.portable.arithmetic.subtract_loop
  (iter : core_models.ops.range.Range Std.Usize) (a : Array Std.I32 8#usize)
  (rhs : simd.portable.vector_type.Coefficients) :
  Result (Array Std.I32 8#usize)
  := do
  loop
    (fun (iter1, a1) => simd.portable.arithmetic.subtract_loop.body rhs iter1
      a1)
    (iter, a)

/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::subtract]:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 24:0-31:1
    Visibility: public -/
def simd.portable.arithmetic.subtract
  (lhs : simd.portable.vector_type.Coefficients)
  (rhs : simd.portable.vector_type.Coefficients) :
  Result simd.portable.vector_type.Coefficients
  := do
  let s ← lift (Array.to_slice lhs.values)
  let i ← core_models.slice.Slice.len s
  let a ←
    simd.portable.arithmetic.subtract_loop { start := 0#usize, «end» := i }
      lhs.values rhs
  ok { values := a }

/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::get_n_least_significant_bits]:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 34:0-36:1 -/
def simd.portable.arithmetic.get_n_least_significant_bits
  (n : Std.U8) (value : Std.U64) : Result Std.U64 := do
  let i ← 1#u64 <<< n
  let i1 ← i - 1#u64
  ok (value &&& i1)

/-- [libcrux_iot_ml_dsa::simd::traits::INVERSE_OF_MODULUS_MOD_MONTGOMERY_R]
    Source: 'ml-dsa/src/simd/traits.rs', lines 14:0-14:64
    Visibility: public -/
@[global_simps, irreducible]
def simd.traits.INVERSE_OF_MODULUS_MOD_MONTGOMERY_R : Std.U64 := 58728449#u64

/-- [libcrux_iot_ml_dsa::simd::traits::FIELD_MODULUS]
    Source: 'ml-dsa/src/simd/traits.rs', lines 11:0-11:41
    Visibility: public -/
@[global_simps, irreducible]
def simd.traits.FIELD_MODULUS : Std.I32 := 8380417#i32

/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::montgomery_reduce_element]:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 39:0-50:1 -/
def simd.portable.arithmetic.montgomery_reduce_element
  (value : Std.I64) : Result Std.I32 := do
  let i ← I64.Insts.Libcrux_secretsIntCastOps.as_u64 value
  let i1 ←
    simd.portable.arithmetic.get_n_least_significant_bits
      simd.portable.arithmetic.MONTGOMERY_SHIFT i
  let t ← i1 * simd.traits.INVERSE_OF_MODULUS_MOD_MONTGOMERY_R
  let i2 ←
    simd.portable.arithmetic.get_n_least_significant_bits
      simd.portable.arithmetic.MONTGOMERY_SHIFT t
  let k ← U64.Insts.Libcrux_secretsIntCastOps.as_i32 i2
  let i3 ← I32.Insts.Libcrux_secretsIntCastOps.as_i64 k
  let i4 ← lift (IScalar.cast .I64 simd.traits.FIELD_MODULUS)
  let i5 ← libcrux_secrets.traits.Classify.Blanket.classify i4
  let k_times_modulus ← i3 * i5
  let i6 ← k_times_modulus >>> simd.portable.arithmetic.MONTGOMERY_SHIFT
  let c ← I64.Insts.Libcrux_secretsIntCastOps.as_i32 i6
  let i7 ← value >>> simd.portable.arithmetic.MONTGOMERY_SHIFT
  let value_high ← I64.Insts.Libcrux_secretsIntCastOps.as_i32 i7
  value_high - c

/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::montgomery_multiply_fe_by_fer]:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 53:0-58:1 -/
def simd.portable.arithmetic.montgomery_multiply_fe_by_fer
  (fe : Std.I32) (fer : Std.I32) : Result Std.I32 := do
  let i ← I32.Insts.Libcrux_secretsIntCastOps.as_i64 fe
  let i1 ← I32.Insts.Libcrux_secretsIntCastOps.as_i64 fer
  let i2 ← i * i1
  simd.portable.arithmetic.montgomery_reduce_element i2

/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::montgomery_multiply_by_constant]: loop body 0:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 62:4-65:5 -/
@[rust_loop_body]
def simd.portable.arithmetic.montgomery_multiply_by_constant_loop.body
  (c : Std.I32) (iter : core_models.ops.range.Range Std.Usize)
  (a : Array Std.I32 8#usize) :
  Result (ControlFlow ((core_models.ops.range.Range Std.Usize) × (Array
    Std.I32 8#usize)) (Array Std.I32 8#usize))
  := do
  let (o, iter1) ←
    core_models.ops.range.Range.Insts.Core_modelsIterTraitsIteratorIterator.next
      Usize.Insts.Core_modelsIterRangeStep iter
  match o with
  | core_models.option.Option.None => ok (done a)
  | core_models.option.Option.Some i =>
    let i1 ← Array.index_usize a i
    let i2 ← I32.Insts.Libcrux_secretsIntCastOps.as_i64 i1
    let i3 ← I32.Insts.Libcrux_secretsIntCastOps.as_i64 c
    let i4 ← i2 * i3
    let i5 ← simd.portable.arithmetic.montgomery_reduce_element i4
    let a1 ← Array.update a i i5
    ok (cont (iter1, a1))

/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::montgomery_multiply_by_constant]: loop 0:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 62:4-65:5 -/
@[rust_loop]
def simd.portable.arithmetic.montgomery_multiply_by_constant_loop
  (iter : core_models.ops.range.Range Std.Usize) (a : Array Std.I32 8#usize)
  (c : Std.I32) :
  Result (Array Std.I32 8#usize)
  := do
  loop
    (fun (iter1, a1) =>
      simd.portable.arithmetic.montgomery_multiply_by_constant_loop.body c
      iter1 a1)
    (iter, a)

/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::montgomery_multiply_by_constant]:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 61:0-69:1 -/
def simd.portable.arithmetic.montgomery_multiply_by_constant
  (simd_unit : simd.portable.vector_type.Coefficients) (c : Std.I32) :
  Result simd.portable.vector_type.Coefficients
  := do
  let s ← lift (Array.to_slice simd_unit.values)
  let i ← core_models.slice.Slice.len s
  let a ←
    simd.portable.arithmetic.montgomery_multiply_by_constant_loop
      { start := 0#usize, «end» := i } simd_unit.values c
  ok { values := a }

/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::montgomery_multiply]: loop body 0:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 73:4-76:5 -/
@[rust_loop_body]
def simd.portable.arithmetic.montgomery_multiply_loop.body
  (rhs : simd.portable.vector_type.Coefficients)
  (iter : core_models.ops.range.Range Std.Usize) (a : Array Std.I32 8#usize) :
  Result (ControlFlow ((core_models.ops.range.Range Std.Usize) × (Array
    Std.I32 8#usize)) (Array Std.I32 8#usize))
  := do
  let (o, iter1) ←
    core_models.ops.range.Range.Insts.Core_modelsIterTraitsIteratorIterator.next
      Usize.Insts.Core_modelsIterRangeStep iter
  match o with
  | core_models.option.Option.None => ok (done a)
  | core_models.option.Option.Some i =>
    let i1 ← Array.index_usize a i
    let i2 ← I32.Insts.Libcrux_secretsIntCastOps.as_i64 i1
    let i3 ← Array.index_usize rhs.values i
    let i4 ← I32.Insts.Libcrux_secretsIntCastOps.as_i64 i3
    let i5 ← i2 * i4
    let i6 ← simd.portable.arithmetic.montgomery_reduce_element i5
    let a1 ← Array.update a i i6
    ok (cont (iter1, a1))

/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::montgomery_multiply]: loop 0:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 73:4-76:5 -/
@[rust_loop]
def simd.portable.arithmetic.montgomery_multiply_loop
  (iter : core_models.ops.range.Range Std.Usize) (a : Array Std.I32 8#usize)
  (rhs : simd.portable.vector_type.Coefficients) :
  Result (Array Std.I32 8#usize)
  := do
  loop
    (fun (iter1, a1) => simd.portable.arithmetic.montgomery_multiply_loop.body
      rhs iter1 a1)
    (iter, a)

/-- [libcrux_iot_ml_dsa::simd::portable::arithmetic::montgomery_multiply]:
    Source: 'ml-dsa/src/simd/portable/arithmetic.rs', lines 72:0-80:1 -/
def simd.portable.arithmetic.montgomery_multiply
  (lhs : simd.portable.vector_type.Coefficients)
  (rhs : simd.portable.vector_type.Coefficients) :
  Result simd.portable.vector_type.Coefficients
  := do
  let s ← lift (Array.to_slice lhs.values)
  let i ← core_models.slice.Slice.len s
  let a ←
    simd.portable.arithmetic.montgomery_multiply_loop
      { start := 0#usize, «end» := i } lhs.values rhs
  ok { values := a }

/-- [libcrux_iot_ml_dsa::simd::portable::invntt::simd_unit_invert_ntt_at_layer_0]:
    Source: 'ml-dsa/src/simd/portable/invntt.rs', lines 8:0-30:1
    Visibility: public -/
def simd.portable.invntt.simd_unit_invert_ntt_at_layer_0
  (simd_unit : simd.portable.vector_type.Coefficients) (zeta0 : Std.I32)
  (zeta1 : Std.I32) (zeta2 : Std.I32) (zeta3 : Std.I32) :
  Result simd.portable.vector_type.Coefficients
  := do
  let i ← Array.index_usize simd_unit.values 1#usize
  let i1 ← Array.index_usize simd_unit.values 0#usize
  let a_minus_b ← i - i1
  let i2 ← i1 + i
  let a ← Array.update simd_unit.values 0#usize i2
  let i3 ← libcrux_secrets.traits.Classify.Blanket.classify zeta0
  let i4 ←
    simd.portable.arithmetic.montgomery_multiply_fe_by_fer a_minus_b i3
  let a1 ← Array.update a 1#usize i4
  let i5 ← Array.index_usize a1 3#usize
  let i6 ← Array.index_usize a1 2#usize
  let a_minus_b1 ← i5 - i6
  let i7 ← i6 + i5
  let a2 ← Array.update a1 2#usize i7
  let i8 ← libcrux_secrets.traits.Classify.Blanket.classify zeta1
  let i9 ←
    simd.portable.arithmetic.montgomery_multiply_fe_by_fer a_minus_b1 i8
  let a3 ← Array.update a2 3#usize i9
  let i10 ← Array.index_usize a3 5#usize
  let i11 ← Array.index_usize a3 4#usize
  let a_minus_b2 ← i10 - i11
  let i12 ← i11 + i10
  let a4 ← Array.update a3 4#usize i12
  let i13 ← libcrux_secrets.traits.Classify.Blanket.classify zeta2
  let i14 ←
    simd.portable.arithmetic.montgomery_multiply_fe_by_fer a_minus_b2 i13
  let a5 ← Array.update a4 5#usize i14
  let i15 ← Array.index_usize a5 7#usize
  let i16 ← Array.index_usize a5 6#usize
  let a_minus_b3 ← i15 - i16
  let i17 ← i16 + i15
  let a6 ← Array.update a5 6#usize i17
  let i18 ← libcrux_secrets.traits.Classify.Blanket.classify zeta3
  let i19 ←
    simd.portable.arithmetic.montgomery_multiply_fe_by_fer a_minus_b3 i18
  let a7 ← Array.update a6 7#usize i19
  ok { values := a7 }

/-- [libcrux_iot_ml_dsa::simd::portable::invntt::simd_unit_invert_ntt_at_layer_1]:
    Source: 'ml-dsa/src/simd/portable/invntt.rs', lines 33:0-49:1
    Visibility: public -/
def simd.portable.invntt.simd_unit_invert_ntt_at_layer_1
  (simd_unit : simd.portable.vector_type.Coefficients) (zeta0 : Std.I32)
  (zeta1 : Std.I32) :
  Result simd.portable.vector_type.Coefficients
  := do
  let i ← Array.index_usize simd_unit.values 2#usize
  let i1 ← Array.index_usize simd_unit.values 0#usize
  let a_minus_b ← i - i1
  let i2 ← i1 + i
  let a ← Array.update simd_unit.values 0#usize i2
  let i3 ← libcrux_secrets.traits.Classify.Blanket.classify zeta0
  let i4 ←
    simd.portable.arithmetic.montgomery_multiply_fe_by_fer a_minus_b i3
  let a1 ← Array.update a 2#usize i4
  let i5 ← Array.index_usize a1 3#usize
  let i6 ← Array.index_usize a1 1#usize
  let a_minus_b1 ← i5 - i6
  let i7 ← i6 + i5
  let a2 ← Array.update a1 1#usize i7
  let i8 ←
    simd.portable.arithmetic.montgomery_multiply_fe_by_fer a_minus_b1 i3
  let a3 ← Array.update a2 3#usize i8
  let i9 ← Array.index_usize a3 6#usize
  let i10 ← Array.index_usize a3 4#usize
  let a_minus_b2 ← i9 - i10
  let i11 ← i10 + i9
  let a4 ← Array.update a3 4#usize i11
  let i12 ← libcrux_secrets.traits.Classify.Blanket.classify zeta1
  let i13 ←
    simd.portable.arithmetic.montgomery_multiply_fe_by_fer a_minus_b2 i12
  let a5 ← Array.update a4 6#usize i13
  let i14 ← Array.index_usize a5 7#usize
  let i15 ← Array.index_usize a5 5#usize
  let a_minus_b3 ← i14 - i15
  let i16 ← i15 + i14
  let a6 ← Array.update a5 5#usize i16
  let i17 ←
    simd.portable.arithmetic.montgomery_multiply_fe_by_fer a_minus_b3 i12
  let a7 ← Array.update a6 7#usize i17
  ok { values := a7 }

/-- [libcrux_iot_ml_dsa::simd::portable::invntt::simd_unit_invert_ntt_at_layer_2]:
    Source: 'ml-dsa/src/simd/portable/invntt.rs', lines 52:0-68:1
    Visibility: public -/
def simd.portable.invntt.simd_unit_invert_ntt_at_layer_2
  (simd_unit : simd.portable.vector_type.Coefficients) (zeta : Std.I32) :
  Result simd.portable.vector_type.Coefficients
  := do
  let i ← Array.index_usize simd_unit.values 4#usize
  let i1 ← Array.index_usize simd_unit.values 0#usize
  let a_minus_b ← i - i1
  let i2 ← i1 + i
  let a ← Array.update simd_unit.values 0#usize i2
  let i3 ← libcrux_secrets.traits.Classify.Blanket.classify zeta
  let i4 ←
    simd.portable.arithmetic.montgomery_multiply_fe_by_fer a_minus_b i3
  let a1 ← Array.update a 4#usize i4
  let i5 ← Array.index_usize a1 5#usize
  let i6 ← Array.index_usize a1 1#usize
  let a_minus_b1 ← i5 - i6
  let i7 ← i6 + i5
  let a2 ← Array.update a1 1#usize i7
  let i8 ←
    simd.portable.arithmetic.montgomery_multiply_fe_by_fer a_minus_b1 i3
  let a3 ← Array.update a2 5#usize i8
  let i9 ← Array.index_usize a3 6#usize
  let i10 ← Array.index_usize a3 2#usize
  let a_minus_b2 ← i9 - i10
  let i11 ← i10 + i9
  let a4 ← Array.update a3 2#usize i11
  let i12 ←
    simd.portable.arithmetic.montgomery_multiply_fe_by_fer a_minus_b2 i3
  let a5 ← Array.update a4 6#usize i12
  let i13 ← Array.index_usize a5 7#usize
  let i14 ← Array.index_usize a5 3#usize
  let a_minus_b3 ← i13 - i14
  let i15 ← i14 + i13
  let a6 ← Array.update a5 3#usize i15
  let i16 ←
    simd.portable.arithmetic.montgomery_multiply_fe_by_fer a_minus_b3 i3
  let a7 ← Array.update a6 7#usize i16
  ok { values := a7 }

/-- [libcrux_iot_ml_dsa::simd::portable::invntt::invert_ntt_at_layer_0::round]:
    Source: 'ml-dsa/src/simd/portable/invntt.rs', lines 73:4-82:5 -/
def simd.portable.invntt.invert_ntt_at_layer_0.round
  (re : Array simd.portable.vector_type.Coefficients 32#usize)
  (index : Std.Usize) (zeta0 : Std.I32) (zeta1 : Std.I32) (zeta2 : Std.I32)
  (zeta3 : Std.I32) :
  Result (Array simd.portable.vector_type.Coefficients 32#usize)
  := do
  let (c, index_mut_back) ← Array.index_mut_usize re index
  let c1 ←
    simd.portable.invntt.simd_unit_invert_ntt_at_layer_0 c zeta0 zeta1 zeta2
      zeta3
  ok (index_mut_back c1)

/-- [libcrux_iot_ml_dsa::simd::portable::invntt::invert_ntt_at_layer_0]:
    Source: 'ml-dsa/src/simd/portable/invntt.rs', lines 71:0-116:1 -/
def simd.portable.invntt.invert_ntt_at_layer_0
  (re : Array simd.portable.vector_type.Coefficients 32#usize) :
  Result (Array simd.portable.vector_type.Coefficients 32#usize)
  := do
  let re1 ←
    simd.portable.invntt.invert_ntt_at_layer_0.round re 0#usize 1976782#i32
      (-846154)#i32 1400424#i32 3937738#i32
  let re2 ←
    simd.portable.invntt.invert_ntt_at_layer_0.round re1 1#usize (-1362209)#i32
      (-48306)#i32 3919660#i32 (-554416)#i32
  let re3 ←
    simd.portable.invntt.invert_ntt_at_layer_0.round re2 2#usize (-3545687)#i32
      1612842#i32 (-976891)#i32 183443#i32
  let re4 ←
    simd.portable.invntt.invert_ntt_at_layer_0.round re3 3#usize (-2286327)#i32
      (-420899)#i32 (-2235985)#i32 (-2939036)#i32
  let re5 ←
    simd.portable.invntt.invert_ntt_at_layer_0.round re4 4#usize (-3833893)#i32
      (-260646)#i32 (-1104333)#i32 (-1667432)#i32
  let re6 ←
    simd.portable.invntt.invert_ntt_at_layer_0.round re5 5#usize 1910376#i32
      (-1803090)#i32 1723600#i32 (-426683)#i32
  let re7 ←
    simd.portable.invntt.invert_ntt_at_layer_0.round re6 6#usize 472078#i32
      1717735#i32 (-975884)#i32 2213111#i32
  let re8 ←
    simd.portable.invntt.invert_ntt_at_layer_0.round re7 7#usize 269760#i32
      3866901#i32 3523897#i32 (-3038916)#i32
  let re9 ←
    simd.portable.invntt.invert_ntt_at_layer_0.round re8 8#usize (-1799107)#i32
      (-3694233)#i32 1652634#i32 810149#i32
  let re10 ←
    simd.portable.invntt.invert_ntt_at_layer_0.round re9 9#usize 3014001#i32
      1616392#i32 162844#i32 (-3183426)#i32
  let re11 ←
    simd.portable.invntt.invert_ntt_at_layer_0.round re10 10#usize
      (-1207385)#i32 185531#i32 3369112#i32 1957272#i32
  let re12 ←
    simd.portable.invntt.invert_ntt_at_layer_0.round re11 11#usize
      (-164721)#i32 2454455#i32 2432395#i32 (-2013608)#i32
  let re13 ←
    simd.portable.invntt.invert_ntt_at_layer_0.round re12 12#usize
      (-3776993)#i32 594136#i32 (-3724270)#i32 (-2584293)#i32
  let re14 ←
    simd.portable.invntt.invert_ntt_at_layer_0.round re13 13#usize
      (-1846953)#i32 (-1671176)#i32 (-2831860)#i32 (-542412)#i32
  let re15 ←
    simd.portable.invntt.invert_ntt_at_layer_0.round re14 14#usize 3406031#i32
      2235880#i32 777191#i32 1500165#i32
  let re16 ←
    simd.portable.invntt.invert_ntt_at_layer_0.round re15 15#usize
      (-1374803)#i32 (-2546312)#i32 1917081#i32 (-1279661)#i32
  let re17 ←
    simd.portable.invntt.invert_ntt_at_layer_0.round re16 16#usize
      (-1962642)#i32 3306115#i32 1312455#i32 (-451100)#i32
  let re18 ←
    simd.portable.invntt.invert_ntt_at_layer_0.round re17 17#usize
      (-1430225)#i32 (-3318210)#i32 1237275#i32 (-1333058)#i32
  let re19 ←
    simd.portable.invntt.invert_ntt_at_layer_0.round re18 18#usize
      (-1050970)#i32 1903435#i32 1869119#i32 (-2994039)#i32
  let re20 ←
    simd.portable.invntt.invert_ntt_at_layer_0.round re19 19#usize
      (-3548272)#i32 2635921#i32 1250494#i32 (-3767016)#i32
  let re21 ←
    simd.portable.invntt.invert_ntt_at_layer_0.round re20 20#usize 1595974#i32
      2486353#i32 1247620#i32 4055324#i32
  let re22 ←
    simd.portable.invntt.invert_ntt_at_layer_0.round re21 21#usize 1265009#i32
      (-2590150)#i32 2691481#i32 2842341#i32
  let re23 ←
    simd.portable.invntt.invert_ntt_at_layer_0.round re22 22#usize 203044#i32
      1735879#i32 (-3342277)#i32 3437287#i32
  let re24 ←
    simd.portable.invntt.invert_ntt_at_layer_0.round re23 23#usize 4108315#i32
      (-2437823)#i32 286988#i32 342297#i32
  let re25 ←
    simd.portable.invntt.invert_ntt_at_layer_0.round re24 24#usize
      (-3595838)#i32 (-768622)#i32 (-525098)#i32 (-3556995)#i32
  let re26 ←
    simd.portable.invntt.invert_ntt_at_layer_0.round re25 25#usize 3207046#i32
      2031748#i32 (-3122442)#i32 (-655327)#i32
  let re27 ←
    simd.portable.invntt.invert_ntt_at_layer_0.round re26 26#usize
      (-522500)#i32 (-43260)#i32 (-1613174)#i32 495491#i32
  let re28 ←
    simd.portable.invntt.invert_ntt_at_layer_0.round re27 27#usize 819034#i32
      909542#i32 1859098#i32 900702#i32
  let re29 ←
    simd.portable.invntt.invert_ntt_at_layer_0.round re28 28#usize
      (-3193378)#i32 (-1197226)#i32 (-3759364)#i32 (-3520352)#i32
  let re30 ←
    simd.portable.invntt.invert_ntt_at_layer_0.round re29 29#usize 3513181#i32
      (-1235728)#i32 2434439#i32 266997#i32
  let re31 ←
    simd.portable.invntt.invert_ntt_at_layer_0.round re30 30#usize
      (-3562462)#i32 (-2446433)#i32 2244091#i32 (-3342478)#i32
  simd.portable.invntt.invert_ntt_at_layer_0.round re31 31#usize 3817976#i32
    2316500#i32 3407706#i32 2091667#i32

/-- [libcrux_iot_ml_dsa::simd::portable::invntt::invert_ntt_at_layer_1::round]:
    Source: 'ml-dsa/src/simd/portable/invntt.rs', lines 121:4-128:5 -/
def simd.portable.invntt.invert_ntt_at_layer_1.round
  (re : Array simd.portable.vector_type.Coefficients 32#usize)
  (index : Std.Usize) (zeta_00 : Std.I32) (zeta_01 : Std.I32) :
  Result (Array simd.portable.vector_type.Coefficients 32#usize)
  := do
  let (c, index_mut_back) ← Array.index_mut_usize re index
  let c1 ←
    simd.portable.invntt.simd_unit_invert_ntt_at_layer_1 c zeta_00 zeta_01
  ok (index_mut_back c1)

/-- [libcrux_iot_ml_dsa::simd::portable::invntt::invert_ntt_at_layer_1]:
    Source: 'ml-dsa/src/simd/portable/invntt.rs', lines 119:0-162:1 -/
def simd.portable.invntt.invert_ntt_at_layer_1
  (re : Array simd.portable.vector_type.Coefficients 32#usize) :
  Result (Array simd.portable.vector_type.Coefficients 32#usize)
  := do
  let re1 ←
    simd.portable.invntt.invert_ntt_at_layer_1.round re 0#usize 3839961#i32
      (-3628969)#i32
  let re2 ←
    simd.portable.invntt.invert_ntt_at_layer_1.round re1 1#usize (-3881060)#i32
      (-3019102)#i32
  let re3 ←
    simd.portable.invntt.invert_ntt_at_layer_1.round re2 2#usize (-1439742)#i32
      (-812732)#i32
  let re4 ←
    simd.portable.invntt.invert_ntt_at_layer_1.round re3 3#usize (-1584928)#i32
      1285669#i32
  let re5 ←
    simd.portable.invntt.invert_ntt_at_layer_1.round re4 4#usize 1341330#i32
      1315589#i32
  let re6 ←
    simd.portable.invntt.invert_ntt_at_layer_1.round re5 5#usize (-177440)#i32
      (-2409325)#i32
  let re7 ←
    simd.portable.invntt.invert_ntt_at_layer_1.round re6 6#usize (-1851402)#i32
      3159746#i32
  let re8 ←
    simd.portable.invntt.invert_ntt_at_layer_1.round re7 7#usize (-3553272)#i32
      189548#i32
  let re9 ←
    simd.portable.invntt.invert_ntt_at_layer_1.round re8 8#usize (-1316856)#i32
      759969#i32
  let re10 ←
    simd.portable.invntt.invert_ntt_at_layer_1.round re9 9#usize (-210977)#i32
      2389356#i32
  let re11 ←
    simd.portable.invntt.invert_ntt_at_layer_1.round re10 10#usize
      (-3249728)#i32 1653064#i32
  let re12 ←
    simd.portable.invntt.invert_ntt_at_layer_1.round re11 11#usize (-8578)#i32
      (-3724342)#i32
  let re13 ←
    simd.portable.invntt.invert_ntt_at_layer_1.round re12 12#usize 3958618#i32
      904516#i32
  let re14 ←
    simd.portable.invntt.invert_ntt_at_layer_1.round re13 13#usize
      (-1100098)#i32 44288#i32
  let re15 ←
    simd.portable.invntt.invert_ntt_at_layer_1.round re14 14#usize 3097992#i32
      508951#i32
  let re16 ←
    simd.portable.invntt.invert_ntt_at_layer_1.round re15 15#usize 264944#i32
      (-3343383)#i32
  let re17 ←
    simd.portable.invntt.invert_ntt_at_layer_1.round re16 16#usize
      (-1430430)#i32 1852771#i32
  let re18 ←
    simd.portable.invntt.invert_ntt_at_layer_1.round re17 17#usize 1349076#i32
      (-381987)#i32
  let re19 ←
    simd.portable.invntt.invert_ntt_at_layer_1.round re18 18#usize
      (-1308169)#i32 (-22981)#i32
  let re20 ←
    simd.portable.invntt.invert_ntt_at_layer_1.round re19 19#usize
      (-1228525)#i32 (-671102)#i32
  let re21 ←
    simd.portable.invntt.invert_ntt_at_layer_1.round re20 20#usize
      (-2477047)#i32 (-411027)#i32
  let re22 ←
    simd.portable.invntt.invert_ntt_at_layer_1.round re21 21#usize
      (-3693493)#i32 (-2967645)#i32
  let re23 ←
    simd.portable.invntt.invert_ntt_at_layer_1.round re22 22#usize 2715295#i32
      2147896#i32
  let re24 ←
    simd.portable.invntt.invert_ntt_at_layer_1.round re23 23#usize
      (-983419)#i32 3412210#i32
  let re25 ←
    simd.portable.invntt.invert_ntt_at_layer_1.round re24 24#usize 126922#i32
      (-3632928)#i32
  let re26 ←
    simd.portable.invntt.invert_ntt_at_layer_1.round re25 25#usize
      (-3157330)#i32 (-3190144)#i32
  let re27 ←
    simd.portable.invntt.invert_ntt_at_layer_1.round re26 26#usize
      (-1000202)#i32 (-4083598)#i32
  let re28 ←
    simd.portable.invntt.invert_ntt_at_layer_1.round re27 27#usize 1939314#i32
      (-1257611)#i32
  let re29 ←
    simd.portable.invntt.invert_ntt_at_layer_1.round re28 28#usize
      (-1585221)#i32 2176455#i32
  let re30 ←
    simd.portable.invntt.invert_ntt_at_layer_1.round re29 29#usize 3475950#i32
      (-1452451)#i32
  let re31 ←
    simd.portable.invntt.invert_ntt_at_layer_1.round re30 30#usize
      (-3041255)#i32 (-3677745)#i32
  simd.portable.invntt.invert_ntt_at_layer_1.round re31 31#usize (-1528703)#i32
    (-3930395)#i32

/-- [libcrux_iot_ml_dsa::simd::portable::invntt::invert_ntt_at_layer_2::round]:
    Source: 'ml-dsa/src/simd/portable/invntt.rs', lines 166:4-168:5 -/
def simd.portable.invntt.invert_ntt_at_layer_2.round
  (re : Array simd.portable.vector_type.Coefficients 32#usize)
  (index : Std.Usize) (zeta1 : Std.I32) :
  Result (Array simd.portable.vector_type.Coefficients 32#usize)
  := do
  let (c, index_mut_back) ← Array.index_mut_usize re index
  let c1 ← simd.portable.invntt.simd_unit_invert_ntt_at_layer_2 c zeta1
  ok (index_mut_back c1)

/-- [libcrux_iot_ml_dsa::simd::portable::invntt::invert_ntt_at_layer_2]:
    Source: 'ml-dsa/src/simd/portable/invntt.rs', lines 165:0-202:1 -/
def simd.portable.invntt.invert_ntt_at_layer_2
  (re : Array simd.portable.vector_type.Coefficients 32#usize) :
  Result (Array simd.portable.vector_type.Coefficients 32#usize)
  := do
  let re1 ←
    simd.portable.invntt.invert_ntt_at_layer_2.round re 0#usize (-2797779)#i32
  let re2 ←
    simd.portable.invntt.invert_ntt_at_layer_2.round re1 1#usize 2071892#i32
  let re3 ←
    simd.portable.invntt.invert_ntt_at_layer_2.round re2 2#usize (-2556880)#i32
  let re4 ←
    simd.portable.invntt.invert_ntt_at_layer_2.round re3 3#usize 3900724#i32
  let re5 ←
    simd.portable.invntt.invert_ntt_at_layer_2.round re4 4#usize 3881043#i32
  let re6 ←
    simd.portable.invntt.invert_ntt_at_layer_2.round re5 5#usize 954230#i32
  let re7 ←
    simd.portable.invntt.invert_ntt_at_layer_2.round re6 6#usize 531354#i32
  let re8 ←
    simd.portable.invntt.invert_ntt_at_layer_2.round re7 7#usize 811944#i32
  let re9 ←
    simd.portable.invntt.invert_ntt_at_layer_2.round re8 8#usize 3699596#i32
  let re10 ←
    simd.portable.invntt.invert_ntt_at_layer_2.round re9 9#usize (-1600420)#i32
  let re11 ←
    simd.portable.invntt.invert_ntt_at_layer_2.round re10 10#usize
      (-2140649)#i32
  let re12 ←
    simd.portable.invntt.invert_ntt_at_layer_2.round re11 11#usize 3507263#i32
  let re13 ←
    simd.portable.invntt.invert_ntt_at_layer_2.round re12 12#usize
      (-3821735)#i32
  let re14 ←
    simd.portable.invntt.invert_ntt_at_layer_2.round re13 13#usize 3505694#i32
  let re15 ←
    simd.portable.invntt.invert_ntt_at_layer_2.round re14 14#usize
      (-1643818)#i32
  let re16 ←
    simd.portable.invntt.invert_ntt_at_layer_2.round re15 15#usize
      (-1699267)#i32
  let re17 ←
    simd.portable.invntt.invert_ntt_at_layer_2.round re16 16#usize
      (-539299)#i32
  let re18 ←
    simd.portable.invntt.invert_ntt_at_layer_2.round re17 17#usize 2348700#i32
  let re19 ←
    simd.portable.invntt.invert_ntt_at_layer_2.round re18 18#usize
      (-300467)#i32
  let re20 ←
    simd.portable.invntt.invert_ntt_at_layer_2.round re19 19#usize 3539968#i32
  let re21 ←
    simd.portable.invntt.invert_ntt_at_layer_2.round re20 20#usize
      (-2867647)#i32
  let re22 ←
    simd.portable.invntt.invert_ntt_at_layer_2.round re21 21#usize 3574422#i32
  let re23 ←
    simd.portable.invntt.invert_ntt_at_layer_2.round re22 22#usize
      (-3043716)#i32
  let re24 ←
    simd.portable.invntt.invert_ntt_at_layer_2.round re23 23#usize
      (-3861115)#i32
  let re25 ←
    simd.portable.invntt.invert_ntt_at_layer_2.round re24 24#usize 3915439#i32
  let re26 ←
    simd.portable.invntt.invert_ntt_at_layer_2.round re25 25#usize
      (-2537516)#i32
  let re27 ←
    simd.portable.invntt.invert_ntt_at_layer_2.round re26 26#usize
      (-3592148)#i32
  let re28 ←
    simd.portable.invntt.invert_ntt_at_layer_2.round re27 27#usize
      (-1661693)#i32
  let re29 ←
    simd.portable.invntt.invert_ntt_at_layer_2.round re28 28#usize 3530437#i32
  let re30 ←
    simd.portable.invntt.invert_ntt_at_layer_2.round re29 29#usize 3077325#i32
  let re31 ←
    simd.portable.invntt.invert_ntt_at_layer_2.round re30 30#usize 95776#i32
  simd.portable.invntt.invert_ntt_at_layer_2.round re31 31#usize 2706023#i32

/-- [libcrux_iot_ml_dsa::simd::portable::vector_type::{core::clone::Clone for libcrux_iot_ml_dsa::simd::portable::vector_type::Coefficients}::clone]:
    Source: 'ml-dsa/src/simd/portable/vector_type.rs', lines 8:9-8:14
    Visibility: public -/
def simd.portable.vector_type.Coefficients.Insts.Core_modelsCloneClone.clone
  (self : simd.portable.vector_type.Coefficients) :
  Result simd.portable.vector_type.Coefficients
  := do
  ok self

/-- [libcrux_iot_ml_dsa::simd::portable::invntt::outer_3_plus]: loop body 0:
    Source: 'ml-dsa/src/simd/portable/invntt.rs', lines 208:4-216:5 -/
@[rust_loop_body]
def simd.portable.invntt.outer_3_plus_loop.body
  (STEP_BY : Std.Usize) (ZETA : Std.I32)
  (iter : core_models.ops.range.Range Std.Usize)
  (re : Array simd.portable.vector_type.Coefficients 32#usize) :
  Result (ControlFlow ((core_models.ops.range.Range Std.Usize) × (Array
    simd.portable.vector_type.Coefficients 32#usize)) (Array
    simd.portable.vector_type.Coefficients 32#usize))
  := do
  let (o, iter1) ←
    core_models.ops.range.Range.Insts.Core_modelsIterTraitsIteratorIterator.next
      Usize.Insts.Core_modelsIterRangeStep iter
  match o with
  | core_models.option.Option.None => ok (done re)
  | core_models.option.Option.Some j =>
    let i ← j + STEP_BY
    let c ← Array.index_usize re i
    let rejs ←
      simd.portable.vector_type.Coefficients.Insts.Core_modelsCloneClone.clone
        c
    let a_minus_b ←
      simd.portable.vector_type.Coefficients.Insts.Core_modelsCloneClone.clone
        rejs
    let c1 ← Array.index_usize re j
    let a_minus_b1 ← simd.portable.arithmetic.subtract a_minus_b c1
    let (c2, index_mut_back) ← Array.index_mut_usize re j
    let c3 ← simd.portable.arithmetic.add c2 rejs
    let re1 := index_mut_back c3
    let re2 ← Array.update re1 i a_minus_b1
    let (c4, index_mut_back1) ← Array.index_mut_usize re2 i
    let i1 ← libcrux_secrets.traits.Classify.Blanket.classify ZETA
    let c5 ← simd.portable.arithmetic.montgomery_multiply_by_constant c4 i1
    let a := index_mut_back1 c5
    ok (cont (iter1, a))

/-- [libcrux_iot_ml_dsa::simd::portable::invntt::outer_3_plus]: loop 0:
    Source: 'ml-dsa/src/simd/portable/invntt.rs', lines 208:4-216:5 -/
@[rust_loop]
def simd.portable.invntt.outer_3_plus_loop
  (STEP_BY : Std.Usize) (ZETA : Std.I32)
  (iter : core_models.ops.range.Range Std.Usize)
  (re : Array simd.portable.vector_type.Coefficients 32#usize) :
  Result (Array simd.portable.vector_type.Coefficients 32#usize)
  := do
  loop
    (fun (iter1, re1) => simd.portable.invntt.outer_3_plus_loop.body STEP_BY
      ZETA iter1 re1)
    (iter, re)

/-- [libcrux_iot_ml_dsa::simd::portable::invntt::outer_3_plus]:
    Source: 'ml-dsa/src/simd/portable/invntt.rs', lines 205:0-220:1 -/
def simd.portable.invntt.outer_3_plus
  (OFFSET : Std.Usize) (STEP_BY : Std.Usize) (ZETA : Std.I32)
  (re : Array simd.portable.vector_type.Coefficients 32#usize) :
  Result (Array simd.portable.vector_type.Coefficients 32#usize)
  := do
  let i ← OFFSET + STEP_BY
  simd.portable.invntt.outer_3_plus_loop STEP_BY ZETA
    { start := OFFSET, «end» := i } re

/-- [libcrux_iot_ml_dsa::simd::portable::invntt::invert_ntt_at_layer_3]:
    Source: 'ml-dsa/src/simd/portable/invntt.rs', lines 223:0-243:1 -/
def simd.portable.invntt.invert_ntt_at_layer_3
  (re : Array simd.portable.vector_type.Coefficients 32#usize) :
  Result (Array simd.portable.vector_type.Coefficients 32#usize)
  := do
  let re1 ← simd.portable.invntt.outer_3_plus 0#usize 1#usize 280005#i32 re
  let re2 ← simd.portable.invntt.outer_3_plus 2#usize 1#usize 4010497#i32 re1
  let re3 ←
    simd.portable.invntt.outer_3_plus 4#usize 1#usize (-19422)#i32 re2
  let re4 ← simd.portable.invntt.outer_3_plus 6#usize 1#usize 1757237#i32 re3
  let re5 ←
    simd.portable.invntt.outer_3_plus 8#usize 1#usize (-3277672)#i32 re4
  let re6 ←
    simd.portable.invntt.outer_3_plus 10#usize 1#usize (-1399561)#i32 re5
  let re7 ←
    simd.portable.invntt.outer_3_plus 12#usize 1#usize (-3859737)#i32 re6
  let re8 ←
    simd.portable.invntt.outer_3_plus 14#usize 1#usize (-2118186)#i32 re7
  let re9 ←
    simd.portable.invntt.outer_3_plus 16#usize 1#usize (-2108549)#i32 re8
  let re10 ←
    simd.portable.invntt.outer_3_plus 18#usize 1#usize 2619752#i32 re9
  let re11 ←
    simd.portable.invntt.outer_3_plus 20#usize 1#usize (-1119584)#i32 re10
  let re12 ←
    simd.portable.invntt.outer_3_plus 22#usize 1#usize (-549488)#i32 re11
  let re13 ←
    simd.portable.invntt.outer_3_plus 24#usize 1#usize 3585928#i32 re12
  let re14 ←
    simd.portable.invntt.outer_3_plus 26#usize 1#usize (-1079900)#i32 re13
  let re15 ←
    simd.portable.invntt.outer_3_plus 28#usize 1#usize 1024112#i32 re14
  simd.portable.invntt.outer_3_plus 30#usize 1#usize 2725464#i32 re15

/-- [libcrux_iot_ml_dsa::simd::portable::invntt::invert_ntt_at_layer_4]:
    Source: 'ml-dsa/src/simd/portable/invntt.rs', lines 246:0-258:1 -/
def simd.portable.invntt.invert_ntt_at_layer_4
  (re : Array simd.portable.vector_type.Coefficients 32#usize) :
  Result (Array simd.portable.vector_type.Coefficients 32#usize)
  := do
  let re1 ← simd.portable.invntt.outer_3_plus 0#usize 2#usize 2680103#i32 re
  let re2 ← simd.portable.invntt.outer_3_plus 4#usize 2#usize 3111497#i32 re1
  let re3 ←
    simd.portable.invntt.outer_3_plus 8#usize 2#usize (-2884855)#i32 re2
  let re4 ←
    simd.portable.invntt.outer_3_plus 12#usize 2#usize 3119733#i32 re3
  let re5 ←
    simd.portable.invntt.outer_3_plus 16#usize 2#usize (-2091905)#i32 re4
  let re6 ←
    simd.portable.invntt.outer_3_plus 20#usize 2#usize (-359251)#i32 re5
  let re7 ←
    simd.portable.invntt.outer_3_plus 24#usize 2#usize 2353451#i32 re6
  simd.portable.invntt.outer_3_plus 28#usize 2#usize 1826347#i32 re7

/-- [libcrux_iot_ml_dsa::simd::portable::invntt::invert_ntt_at_layer_5]:
    Source: 'ml-dsa/src/simd/portable/invntt.rs', lines 261:0-269:1 -/
def simd.portable.invntt.invert_ntt_at_layer_5
  (re : Array simd.portable.vector_type.Coefficients 32#usize) :
  Result (Array simd.portable.vector_type.Coefficients 32#usize)
  := do
  let re1 ← simd.portable.invntt.outer_3_plus 0#usize 4#usize 466468#i32 re
  let re2 ←
    simd.portable.invntt.outer_3_plus 8#usize 4#usize (-876248)#i32 re1
  let re3 ←
    simd.portable.invntt.outer_3_plus 16#usize 4#usize (-777960)#i32 re2
  simd.portable.invntt.outer_3_plus 24#usize 4#usize 237124#i32 re3

/-- [libcrux_iot_ml_dsa::simd::portable::invntt::invert_ntt_at_layer_6]:
    Source: 'ml-dsa/src/simd/portable/invntt.rs', lines 272:0-278:1 -/
def simd.portable.invntt.invert_ntt_at_layer_6
  (re : Array simd.portable.vector_type.Coefficients 32#usize) :
  Result (Array simd.portable.vector_type.Coefficients 32#usize)
  := do
  let re1 ←
    simd.portable.invntt.outer_3_plus 0#usize 8#usize (-518909)#i32 re
  simd.portable.invntt.outer_3_plus 16#usize 8#usize (-2608894)#i32 re1

/-- [libcrux_iot_ml_dsa::simd::portable::invntt::invert_ntt_at_layer_7]:
    Source: 'ml-dsa/src/simd/portable/invntt.rs', lines 281:0-286:1 -/
def simd.portable.invntt.invert_ntt_at_layer_7
  (re : Array simd.portable.vector_type.Coefficients 32#usize) :
  Result (Array simd.portable.vector_type.Coefficients 32#usize)
  := do
  simd.portable.invntt.outer_3_plus 0#usize 16#usize 25847#i32 re

/-- [libcrux_iot_ml_dsa::simd::portable::invntt::invert_ntt_montgomery]: loop body 0:
    Source: 'ml-dsa/src/simd/portable/invntt.rs', lines 298:4-305:5 -/
@[rust_loop_body]
def simd.portable.invntt.invert_ntt_montgomery_loop.body
  (iter : core_models.ops.range.Range Std.Usize)
  (re : Array simd.portable.vector_type.Coefficients 32#usize) :
  Result (ControlFlow ((core_models.ops.range.Range Std.Usize) × (Array
    simd.portable.vector_type.Coefficients 32#usize)) (Array
    simd.portable.vector_type.Coefficients 32#usize))
  := do
  let (o, iter1) ←
    core_models.ops.range.Range.Insts.Core_modelsIterTraitsIteratorIterator.next
      Usize.Insts.Core_modelsIterRangeStep iter
  match o with
  | core_models.option.Option.None => ok (done re)
  | core_models.option.Option.Some i =>
    let (c, index_mut_back) ← Array.index_mut_usize re i
    let i1 ← libcrux_secrets.traits.Classify.Blanket.classify 41978#i32
    let c1 ← simd.portable.arithmetic.montgomery_multiply_by_constant c i1
    let a := index_mut_back c1
    ok (cont (iter1, a))

/-- [libcrux_iot_ml_dsa::simd::portable::invntt::invert_ntt_montgomery]: loop 0:
    Source: 'ml-dsa/src/simd/portable/invntt.rs', lines 298:4-305:5 -/
@[rust_loop]
def simd.portable.invntt.invert_ntt_montgomery_loop
  (iter : core_models.ops.range.Range Std.Usize)
  (re : Array simd.portable.vector_type.Coefficients 32#usize) :
  Result (Array simd.portable.vector_type.Coefficients 32#usize)
  := do
  loop
    (fun (iter1, re1) => simd.portable.invntt.invert_ntt_montgomery_loop.body
      iter1 re1)
    (iter, re)

/-- [libcrux_iot_ml_dsa::simd::portable::invntt::invert_ntt_montgomery]:
    Source: 'ml-dsa/src/simd/portable/invntt.rs', lines 288:0-309:1 -/
def simd.portable.invntt.invert_ntt_montgomery
  (re : Array simd.portable.vector_type.Coefficients 32#usize) :
  Result (Array simd.portable.vector_type.Coefficients 32#usize)
  := do
  let re1 ← simd.portable.invntt.invert_ntt_at_layer_0 re
  let re2 ← simd.portable.invntt.invert_ntt_at_layer_1 re1
  let re3 ← simd.portable.invntt.invert_ntt_at_layer_2 re2
  let re4 ← simd.portable.invntt.invert_ntt_at_layer_3 re3
  let re5 ← simd.portable.invntt.invert_ntt_at_layer_4 re4
  let re6 ← simd.portable.invntt.invert_ntt_at_layer_5 re5
  let re7 ← simd.portable.invntt.invert_ntt_at_layer_6 re6
  let re8 ← simd.portable.invntt.invert_ntt_at_layer_7 re7
  let s ← lift (Array.to_slice re8)
  let i ← core_models.slice.Slice.len s
  simd.portable.invntt.invert_ntt_montgomery_loop
    { start := 0#usize, «end» := i } re8

/-- [libcrux_iot_ml_dsa::simd::portable::ntt::simd_unit_ntt_at_layer_0]:
    Source: 'ml-dsa/src/simd/portable/ntt.rs', lines 8:0-30:1
    Visibility: public -/
def simd.portable.ntt.simd_unit_ntt_at_layer_0
  (simd_unit : simd.portable.vector_type.Coefficients) (zeta0 : Std.I32)
  (zeta1 : Std.I32) (zeta2 : Std.I32) (zeta3 : Std.I32) :
  Result simd.portable.vector_type.Coefficients
  := do
  let i ← Array.index_usize simd_unit.values 1#usize
  let i1 ← libcrux_secrets.traits.Classify.Blanket.classify zeta0
  let t ← simd.portable.arithmetic.montgomery_multiply_fe_by_fer i i1
  let i2 ← Array.index_usize simd_unit.values 0#usize
  let i3 ← i2 - t
  let a ← Array.update simd_unit.values 1#usize i3
  let i4 ← Array.index_usize a 0#usize
  let i5 ← i4 + t
  let a1 ← Array.update a 0#usize i5
  let i6 ← Array.index_usize a1 3#usize
  let i7 ← libcrux_secrets.traits.Classify.Blanket.classify zeta1
  let t1 ← simd.portable.arithmetic.montgomery_multiply_fe_by_fer i6 i7
  let i8 ← Array.index_usize a1 2#usize
  let i9 ← i8 - t1
  let a2 ← Array.update a1 3#usize i9
  let i10 ← Array.index_usize a2 2#usize
  let i11 ← i10 + t1
  let a3 ← Array.update a2 2#usize i11
  let i12 ← Array.index_usize a3 5#usize
  let i13 ← libcrux_secrets.traits.Classify.Blanket.classify zeta2
  let t2 ← simd.portable.arithmetic.montgomery_multiply_fe_by_fer i12 i13
  let i14 ← Array.index_usize a3 4#usize
  let i15 ← i14 - t2
  let a4 ← Array.update a3 5#usize i15
  let i16 ← Array.index_usize a4 4#usize
  let i17 ← i16 + t2
  let a5 ← Array.update a4 4#usize i17
  let i18 ← Array.index_usize a5 7#usize
  let i19 ← libcrux_secrets.traits.Classify.Blanket.classify zeta3
  let t3 ← simd.portable.arithmetic.montgomery_multiply_fe_by_fer i18 i19
  let i20 ← Array.index_usize a5 6#usize
  let i21 ← i20 - t3
  let a6 ← Array.update a5 7#usize i21
  let i22 ← Array.index_usize a6 6#usize
  let i23 ← i22 + t3
  let a7 ← Array.update a6 6#usize i23
  ok { values := a7 }

/-- [libcrux_iot_ml_dsa::simd::portable::ntt::simd_unit_ntt_at_layer_1]:
    Source: 'ml-dsa/src/simd/portable/ntt.rs', lines 33:0-49:1
    Visibility: public -/
def simd.portable.ntt.simd_unit_ntt_at_layer_1
  (simd_unit : simd.portable.vector_type.Coefficients) (zeta1 : Std.I32)
  (zeta2 : Std.I32) :
  Result simd.portable.vector_type.Coefficients
  := do
  let i ← Array.index_usize simd_unit.values 2#usize
  let i1 ← libcrux_secrets.traits.Classify.Blanket.classify zeta1
  let t ← simd.portable.arithmetic.montgomery_multiply_fe_by_fer i i1
  let i2 ← Array.index_usize simd_unit.values 0#usize
  let i3 ← i2 - t
  let a ← Array.update simd_unit.values 2#usize i3
  let i4 ← Array.index_usize a 0#usize
  let i5 ← i4 + t
  let a1 ← Array.update a 0#usize i5
  let i6 ← Array.index_usize a1 3#usize
  let t1 ← simd.portable.arithmetic.montgomery_multiply_fe_by_fer i6 i1
  let i7 ← Array.index_usize a1 1#usize
  let i8 ← i7 - t1
  let a2 ← Array.update a1 3#usize i8
  let i9 ← Array.index_usize a2 1#usize
  let i10 ← i9 + t1
  let a3 ← Array.update a2 1#usize i10
  let i11 ← Array.index_usize a3 6#usize
  let i12 ← libcrux_secrets.traits.Classify.Blanket.classify zeta2
  let t2 ← simd.portable.arithmetic.montgomery_multiply_fe_by_fer i11 i12
  let i13 ← Array.index_usize a3 4#usize
  let i14 ← i13 - t2
  let a4 ← Array.update a3 6#usize i14
  let i15 ← Array.index_usize a4 4#usize
  let i16 ← i15 + t2
  let a5 ← Array.update a4 4#usize i16
  let i17 ← Array.index_usize a5 7#usize
  let t3 ← simd.portable.arithmetic.montgomery_multiply_fe_by_fer i17 i12
  let i18 ← Array.index_usize a5 5#usize
  let i19 ← i18 - t3
  let a6 ← Array.update a5 7#usize i19
  let i20 ← Array.index_usize a6 5#usize
  let i21 ← i20 + t3
  let a7 ← Array.update a6 5#usize i21
  ok { values := a7 }

/-- [libcrux_iot_ml_dsa::simd::portable::ntt::simd_unit_ntt_at_layer_2]:
    Source: 'ml-dsa/src/simd/portable/ntt.rs', lines 52:0-68:1
    Visibility: public -/
def simd.portable.ntt.simd_unit_ntt_at_layer_2
  (simd_unit : simd.portable.vector_type.Coefficients) (zeta : Std.I32) :
  Result simd.portable.vector_type.Coefficients
  := do
  let i ← Array.index_usize simd_unit.values 4#usize
  let i1 ← libcrux_secrets.traits.Classify.Blanket.classify zeta
  let t ← simd.portable.arithmetic.montgomery_multiply_fe_by_fer i i1
  let i2 ← Array.index_usize simd_unit.values 0#usize
  let i3 ← i2 - t
  let a ← Array.update simd_unit.values 4#usize i3
  let i4 ← Array.index_usize a 0#usize
  let i5 ← i4 + t
  let a1 ← Array.update a 0#usize i5
  let i6 ← Array.index_usize a1 5#usize
  let t1 ← simd.portable.arithmetic.montgomery_multiply_fe_by_fer i6 i1
  let i7 ← Array.index_usize a1 1#usize
  let i8 ← i7 - t1
  let a2 ← Array.update a1 5#usize i8
  let i9 ← Array.index_usize a2 1#usize
  let i10 ← i9 + t1
  let a3 ← Array.update a2 1#usize i10
  let i11 ← Array.index_usize a3 6#usize
  let t2 ← simd.portable.arithmetic.montgomery_multiply_fe_by_fer i11 i1
  let i12 ← Array.index_usize a3 2#usize
  let i13 ← i12 - t2
  let a4 ← Array.update a3 6#usize i13
  let i14 ← Array.index_usize a4 2#usize
  let i15 ← i14 + t2
  let a5 ← Array.update a4 2#usize i15
  let i16 ← Array.index_usize a5 7#usize
  let t3 ← simd.portable.arithmetic.montgomery_multiply_fe_by_fer i16 i1
  let i17 ← Array.index_usize a5 3#usize
  let i18 ← i17 - t3
  let a6 ← Array.update a5 7#usize i18
  let i19 ← Array.index_usize a6 3#usize
  let i20 ← i19 + t3
  let a7 ← Array.update a6 3#usize i20
  ok { values := a7 }

/-- [libcrux_iot_ml_dsa::simd::portable::ntt::ntt_at_layer_0::round]:
    Source: 'ml-dsa/src/simd/portable/ntt.rs', lines 73:4-82:5 -/
def simd.portable.ntt.ntt_at_layer_0.round
  (re : Array simd.portable.vector_type.Coefficients 32#usize)
  (index : Std.Usize) (zeta_0 : Std.I32) (zeta_1 : Std.I32) (zeta_2 : Std.I32)
  (zeta_3 : Std.I32) :
  Result (Array simd.portable.vector_type.Coefficients 32#usize)
  := do
  let (c, index_mut_back) ← Array.index_mut_usize re index
  let c1 ←
    simd.portable.ntt.simd_unit_ntt_at_layer_0 c zeta_0 zeta_1 zeta_2 zeta_3
  ok (index_mut_back c1)

/-- [libcrux_iot_ml_dsa::simd::portable::ntt::ntt_at_layer_0]:
    Source: 'ml-dsa/src/simd/portable/ntt.rs', lines 71:0-116:1 -/
def simd.portable.ntt.ntt_at_layer_0
  (re : Array simd.portable.vector_type.Coefficients 32#usize) :
  Result (Array simd.portable.vector_type.Coefficients 32#usize)
  := do
  let re1 ←
    simd.portable.ntt.ntt_at_layer_0.round re 0#usize 2091667#i32 3407706#i32
      2316500#i32 3817976#i32
  let re2 ←
    simd.portable.ntt.ntt_at_layer_0.round re1 1#usize (-3342478)#i32
      2244091#i32 (-2446433)#i32 (-3562462)#i32
  let re3 ←
    simd.portable.ntt.ntt_at_layer_0.round re2 2#usize 266997#i32 2434439#i32
      (-1235728)#i32 3513181#i32
  let re4 ←
    simd.portable.ntt.ntt_at_layer_0.round re3 3#usize (-3520352)#i32
      (-3759364)#i32 (-1197226)#i32 (-3193378)#i32
  let re5 ←
    simd.portable.ntt.ntt_at_layer_0.round re4 4#usize 900702#i32 1859098#i32
      909542#i32 819034#i32
  let re6 ←
    simd.portable.ntt.ntt_at_layer_0.round re5 5#usize 495491#i32
      (-1613174)#i32 (-43260)#i32 (-522500)#i32
  let re7 ←
    simd.portable.ntt.ntt_at_layer_0.round re6 6#usize (-655327)#i32
      (-3122442)#i32 2031748#i32 3207046#i32
  let re8 ←
    simd.portable.ntt.ntt_at_layer_0.round re7 7#usize (-3556995)#i32
      (-525098)#i32 (-768622)#i32 (-3595838)#i32
  let re9 ←
    simd.portable.ntt.ntt_at_layer_0.round re8 8#usize 342297#i32 286988#i32
      (-2437823)#i32 4108315#i32
  let re10 ←
    simd.portable.ntt.ntt_at_layer_0.round re9 9#usize 3437287#i32
      (-3342277)#i32 1735879#i32 203044#i32
  let re11 ←
    simd.portable.ntt.ntt_at_layer_0.round re10 10#usize 2842341#i32
      2691481#i32 (-2590150)#i32 1265009#i32
  let re12 ←
    simd.portable.ntt.ntt_at_layer_0.round re11 11#usize 4055324#i32
      1247620#i32 2486353#i32 1595974#i32
  let re13 ←
    simd.portable.ntt.ntt_at_layer_0.round re12 12#usize (-3767016)#i32
      1250494#i32 2635921#i32 (-3548272)#i32
  let re14 ←
    simd.portable.ntt.ntt_at_layer_0.round re13 13#usize (-2994039)#i32
      1869119#i32 1903435#i32 (-1050970)#i32
  let re15 ←
    simd.portable.ntt.ntt_at_layer_0.round re14 14#usize (-1333058)#i32
      1237275#i32 (-3318210)#i32 (-1430225)#i32
  let re16 ←
    simd.portable.ntt.ntt_at_layer_0.round re15 15#usize (-451100)#i32
      1312455#i32 3306115#i32 (-1962642)#i32
  let re17 ←
    simd.portable.ntt.ntt_at_layer_0.round re16 16#usize (-1279661)#i32
      1917081#i32 (-2546312)#i32 (-1374803)#i32
  let re18 ←
    simd.portable.ntt.ntt_at_layer_0.round re17 17#usize 1500165#i32 777191#i32
      2235880#i32 3406031#i32
  let re19 ←
    simd.portable.ntt.ntt_at_layer_0.round re18 18#usize (-542412)#i32
      (-2831860)#i32 (-1671176)#i32 (-1846953)#i32
  let re20 ←
    simd.portable.ntt.ntt_at_layer_0.round re19 19#usize (-2584293)#i32
      (-3724270)#i32 594136#i32 (-3776993)#i32
  let re21 ←
    simd.portable.ntt.ntt_at_layer_0.round re20 20#usize (-2013608)#i32
      2432395#i32 2454455#i32 (-164721)#i32
  let re22 ←
    simd.portable.ntt.ntt_at_layer_0.round re21 21#usize 1957272#i32
      3369112#i32 185531#i32 (-1207385)#i32
  let re23 ←
    simd.portable.ntt.ntt_at_layer_0.round re22 22#usize (-3183426)#i32
      162844#i32 1616392#i32 3014001#i32
  let re24 ←
    simd.portable.ntt.ntt_at_layer_0.round re23 23#usize 810149#i32 1652634#i32
      (-3694233)#i32 (-1799107)#i32
  let re25 ←
    simd.portable.ntt.ntt_at_layer_0.round re24 24#usize (-3038916)#i32
      3523897#i32 3866901#i32 269760#i32
  let re26 ←
    simd.portable.ntt.ntt_at_layer_0.round re25 25#usize 2213111#i32
      (-975884)#i32 1717735#i32 472078#i32
  let re27 ←
    simd.portable.ntt.ntt_at_layer_0.round re26 26#usize (-426683)#i32
      1723600#i32 (-1803090)#i32 1910376#i32
  let re28 ←
    simd.portable.ntt.ntt_at_layer_0.round re27 27#usize (-1667432)#i32
      (-1104333)#i32 (-260646)#i32 (-3833893)#i32
  let re29 ←
    simd.portable.ntt.ntt_at_layer_0.round re28 28#usize (-2939036)#i32
      (-2235985)#i32 (-420899)#i32 (-2286327)#i32
  let re30 ←
    simd.portable.ntt.ntt_at_layer_0.round re29 29#usize 183443#i32
      (-976891)#i32 1612842#i32 (-3545687)#i32
  let re31 ←
    simd.portable.ntt.ntt_at_layer_0.round re30 30#usize (-554416)#i32
      3919660#i32 (-48306)#i32 (-1362209)#i32
  simd.portable.ntt.ntt_at_layer_0.round re31 31#usize 3937738#i32 1400424#i32
    (-846154)#i32 1976782#i32

/-- [libcrux_iot_ml_dsa::simd::portable::ntt::ntt_at_layer_1::round]:
    Source: 'ml-dsa/src/simd/portable/ntt.rs', lines 121:4-128:5 -/
def simd.portable.ntt.ntt_at_layer_1.round
  (re : Array simd.portable.vector_type.Coefficients 32#usize)
  (index : Std.Usize) (zeta_0 : Std.I32) (zeta_1 : Std.I32) :
  Result (Array simd.portable.vector_type.Coefficients 32#usize)
  := do
  let (c, index_mut_back) ← Array.index_mut_usize re index
  let c1 ← simd.portable.ntt.simd_unit_ntt_at_layer_1 c zeta_0 zeta_1
  ok (index_mut_back c1)

/-- [libcrux_iot_ml_dsa::simd::portable::ntt::ntt_at_layer_1]:
    Source: 'ml-dsa/src/simd/portable/ntt.rs', lines 119:0-162:1 -/
def simd.portable.ntt.ntt_at_layer_1
  (re : Array simd.portable.vector_type.Coefficients 32#usize) :
  Result (Array simd.portable.vector_type.Coefficients 32#usize)
  := do
  let re1 ←
    simd.portable.ntt.ntt_at_layer_1.round re 0#usize (-3930395)#i32
      (-1528703)#i32
  let re2 ←
    simd.portable.ntt.ntt_at_layer_1.round re1 1#usize (-3677745)#i32
      (-3041255)#i32
  let re3 ←
    simd.portable.ntt.ntt_at_layer_1.round re2 2#usize (-1452451)#i32
      3475950#i32
  let re4 ←
    simd.portable.ntt.ntt_at_layer_1.round re3 3#usize 2176455#i32
      (-1585221)#i32
  let re5 ←
    simd.portable.ntt.ntt_at_layer_1.round re4 4#usize (-1257611)#i32
      1939314#i32
  let re6 ←
    simd.portable.ntt.ntt_at_layer_1.round re5 5#usize (-4083598)#i32
      (-1000202)#i32
  let re7 ←
    simd.portable.ntt.ntt_at_layer_1.round re6 6#usize (-3190144)#i32
      (-3157330)#i32
  let re8 ←
    simd.portable.ntt.ntt_at_layer_1.round re7 7#usize (-3632928)#i32
      126922#i32
  let re9 ←
    simd.portable.ntt.ntt_at_layer_1.round re8 8#usize 3412210#i32
      (-983419)#i32
  let re10 ←
    simd.portable.ntt.ntt_at_layer_1.round re9 9#usize 2147896#i32 2715295#i32
  let re11 ←
    simd.portable.ntt.ntt_at_layer_1.round re10 10#usize (-2967645)#i32
      (-3693493)#i32
  let re12 ←
    simd.portable.ntt.ntt_at_layer_1.round re11 11#usize (-411027)#i32
      (-2477047)#i32
  let re13 ←
    simd.portable.ntt.ntt_at_layer_1.round re12 12#usize (-671102)#i32
      (-1228525)#i32
  let re14 ←
    simd.portable.ntt.ntt_at_layer_1.round re13 13#usize (-22981)#i32
      (-1308169)#i32
  let re15 ←
    simd.portable.ntt.ntt_at_layer_1.round re14 14#usize (-381987)#i32
      1349076#i32
  let re16 ←
    simd.portable.ntt.ntt_at_layer_1.round re15 15#usize 1852771#i32
      (-1430430)#i32
  let re17 ←
    simd.portable.ntt.ntt_at_layer_1.round re16 16#usize (-3343383)#i32
      264944#i32
  let re18 ←
    simd.portable.ntt.ntt_at_layer_1.round re17 17#usize 508951#i32 3097992#i32
  let re19 ←
    simd.portable.ntt.ntt_at_layer_1.round re18 18#usize 44288#i32
      (-1100098)#i32
  let re20 ←
    simd.portable.ntt.ntt_at_layer_1.round re19 19#usize 904516#i32 3958618#i32
  let re21 ←
    simd.portable.ntt.ntt_at_layer_1.round re20 20#usize (-3724342)#i32
      (-8578)#i32
  let re22 ←
    simd.portable.ntt.ntt_at_layer_1.round re21 21#usize 1653064#i32
      (-3249728)#i32
  let re23 ←
    simd.portable.ntt.ntt_at_layer_1.round re22 22#usize 2389356#i32
      (-210977)#i32
  let re24 ←
    simd.portable.ntt.ntt_at_layer_1.round re23 23#usize 759969#i32
      (-1316856)#i32
  let re25 ←
    simd.portable.ntt.ntt_at_layer_1.round re24 24#usize 189548#i32
      (-3553272)#i32
  let re26 ←
    simd.portable.ntt.ntt_at_layer_1.round re25 25#usize 3159746#i32
      (-1851402)#i32
  let re27 ←
    simd.portable.ntt.ntt_at_layer_1.round re26 26#usize (-2409325)#i32
      (-177440)#i32
  let re28 ←
    simd.portable.ntt.ntt_at_layer_1.round re27 27#usize 1315589#i32
      1341330#i32
  let re29 ←
    simd.portable.ntt.ntt_at_layer_1.round re28 28#usize 1285669#i32
      (-1584928)#i32
  let re30 ←
    simd.portable.ntt.ntt_at_layer_1.round re29 29#usize (-812732)#i32
      (-1439742)#i32
  let re31 ←
    simd.portable.ntt.ntt_at_layer_1.round re30 30#usize (-3019102)#i32
      (-3881060)#i32
  simd.portable.ntt.ntt_at_layer_1.round re31 31#usize (-3628969)#i32
    3839961#i32

/-- [libcrux_iot_ml_dsa::simd::portable::ntt::ntt_at_layer_2::round]:
    Source: 'ml-dsa/src/simd/portable/ntt.rs', lines 167:4-169:5 -/
def simd.portable.ntt.ntt_at_layer_2.round
  (re : Array simd.portable.vector_type.Coefficients 32#usize)
  (index : Std.Usize) (zeta : Std.I32) :
  Result (Array simd.portable.vector_type.Coefficients 32#usize)
  := do
  let (c, index_mut_back) ← Array.index_mut_usize re index
  let c1 ← simd.portable.ntt.simd_unit_ntt_at_layer_2 c zeta
  ok (index_mut_back c1)

/-- [libcrux_iot_ml_dsa::simd::portable::ntt::ntt_at_layer_2]:
    Source: 'ml-dsa/src/simd/portable/ntt.rs', lines 165:0-203:1 -/
def simd.portable.ntt.ntt_at_layer_2
  (re : Array simd.portable.vector_type.Coefficients 32#usize) :
  Result (Array simd.portable.vector_type.Coefficients 32#usize)
  := do
  let re1 ← simd.portable.ntt.ntt_at_layer_2.round re 0#usize 2706023#i32
  let re2 ← simd.portable.ntt.ntt_at_layer_2.round re1 1#usize 95776#i32
  let re3 ← simd.portable.ntt.ntt_at_layer_2.round re2 2#usize 3077325#i32
  let re4 ← simd.portable.ntt.ntt_at_layer_2.round re3 3#usize 3530437#i32
  let re5 ← simd.portable.ntt.ntt_at_layer_2.round re4 4#usize (-1661693)#i32
  let re6 ← simd.portable.ntt.ntt_at_layer_2.round re5 5#usize (-3592148)#i32
  let re7 ← simd.portable.ntt.ntt_at_layer_2.round re6 6#usize (-2537516)#i32
  let re8 ← simd.portable.ntt.ntt_at_layer_2.round re7 7#usize 3915439#i32
  let re9 ← simd.portable.ntt.ntt_at_layer_2.round re8 8#usize (-3861115)#i32
  let re10 ←
    simd.portable.ntt.ntt_at_layer_2.round re9 9#usize (-3043716)#i32
  let re11 ← simd.portable.ntt.ntt_at_layer_2.round re10 10#usize 3574422#i32
  let re12 ←
    simd.portable.ntt.ntt_at_layer_2.round re11 11#usize (-2867647)#i32
  let re13 ← simd.portable.ntt.ntt_at_layer_2.round re12 12#usize 3539968#i32
  let re14 ←
    simd.portable.ntt.ntt_at_layer_2.round re13 13#usize (-300467)#i32
  let re15 ← simd.portable.ntt.ntt_at_layer_2.round re14 14#usize 2348700#i32
  let re16 ←
    simd.portable.ntt.ntt_at_layer_2.round re15 15#usize (-539299)#i32
  let re17 ←
    simd.portable.ntt.ntt_at_layer_2.round re16 16#usize (-1699267)#i32
  let re18 ←
    simd.portable.ntt.ntt_at_layer_2.round re17 17#usize (-1643818)#i32
  let re19 ← simd.portable.ntt.ntt_at_layer_2.round re18 18#usize 3505694#i32
  let re20 ←
    simd.portable.ntt.ntt_at_layer_2.round re19 19#usize (-3821735)#i32
  let re21 ← simd.portable.ntt.ntt_at_layer_2.round re20 20#usize 3507263#i32
  let re22 ←
    simd.portable.ntt.ntt_at_layer_2.round re21 21#usize (-2140649)#i32
  let re23 ←
    simd.portable.ntt.ntt_at_layer_2.round re22 22#usize (-1600420)#i32
  let re24 ← simd.portable.ntt.ntt_at_layer_2.round re23 23#usize 3699596#i32
  let re25 ← simd.portable.ntt.ntt_at_layer_2.round re24 24#usize 811944#i32
  let re26 ← simd.portable.ntt.ntt_at_layer_2.round re25 25#usize 531354#i32
  let re27 ← simd.portable.ntt.ntt_at_layer_2.round re26 26#usize 954230#i32
  let re28 ← simd.portable.ntt.ntt_at_layer_2.round re27 27#usize 3881043#i32
  let re29 ← simd.portable.ntt.ntt_at_layer_2.round re28 28#usize 3900724#i32
  let re30 ←
    simd.portable.ntt.ntt_at_layer_2.round re29 29#usize (-2556880)#i32
  let re31 ← simd.portable.ntt.ntt_at_layer_2.round re30 30#usize 2071892#i32
  simd.portable.ntt.ntt_at_layer_2.round re31 31#usize (-2797779)#i32

/-- [libcrux_iot_ml_dsa::simd::portable::ntt::outer_3_plus]: loop body 0:
    Source: 'ml-dsa/src/simd/portable/ntt.rs', lines 209:4-216:5 -/
@[rust_loop_body]
def simd.portable.ntt.outer_3_plus_loop.body
  (STEP_BY : Std.Usize) (ZETA : Std.I32)
  (iter : core_models.ops.range.Range Std.Usize)
  (re : Array simd.portable.vector_type.Coefficients 32#usize) :
  Result (ControlFlow ((core_models.ops.range.Range Std.Usize) × (Array
    simd.portable.vector_type.Coefficients 32#usize)) (Array
    simd.portable.vector_type.Coefficients 32#usize))
  := do
  let (o, iter1) ←
    core_models.ops.range.Range.Insts.Core_modelsIterTraitsIteratorIterator.next
      Usize.Insts.Core_modelsIterRangeStep iter
  match o with
  | core_models.option.Option.None => ok (done re)
  | core_models.option.Option.Some j =>
    let i ← j + STEP_BY
    let tmp ← Array.index_usize re i
    let i1 ← libcrux_secrets.traits.Classify.Blanket.classify ZETA
    let tmp1 ←
      simd.portable.arithmetic.montgomery_multiply_by_constant tmp i1
    let c ← Array.index_usize re j
    let re1 ← Array.update re i c
    let (c1, index_mut_back) ← Array.index_mut_usize re1 i
    let c2 ← simd.portable.arithmetic.subtract c1 tmp1
    let re2 := index_mut_back c2
    let (c3, index_mut_back1) ← Array.index_mut_usize re2 j
    let c4 ← simd.portable.arithmetic.add c3 tmp1
    let a := index_mut_back1 c4
    ok (cont (iter1, a))

/-- [libcrux_iot_ml_dsa::simd::portable::ntt::outer_3_plus]: loop 0:
    Source: 'ml-dsa/src/simd/portable/ntt.rs', lines 209:4-216:5 -/
@[rust_loop]
def simd.portable.ntt.outer_3_plus_loop
  (STEP_BY : Std.Usize) (ZETA : Std.I32)
  (iter : core_models.ops.range.Range Std.Usize)
  (re : Array simd.portable.vector_type.Coefficients 32#usize) :
  Result (Array simd.portable.vector_type.Coefficients 32#usize)
  := do
  loop
    (fun (iter1, re1) => simd.portable.ntt.outer_3_plus_loop.body STEP_BY ZETA
      iter1 re1)
    (iter, re)

/-- [libcrux_iot_ml_dsa::simd::portable::ntt::outer_3_plus]:
    Source: 'ml-dsa/src/simd/portable/ntt.rs', lines 206:0-218:1 -/
def simd.portable.ntt.outer_3_plus
  (OFFSET : Std.Usize) (STEP_BY : Std.Usize) (ZETA : Std.I32)
  (re : Array simd.portable.vector_type.Coefficients 32#usize) :
  Result (Array simd.portable.vector_type.Coefficients 32#usize)
  := do
  let i ← OFFSET + STEP_BY
  simd.portable.ntt.outer_3_plus_loop STEP_BY ZETA
    { start := OFFSET, «end» := i } re

/-- [libcrux_iot_ml_dsa::simd::portable::ntt::ntt_at_layer_3]:
    Source: 'ml-dsa/src/simd/portable/ntt.rs', lines 221:0-241:1 -/
def simd.portable.ntt.ntt_at_layer_3
  (re : Array simd.portable.vector_type.Coefficients 32#usize) :
  Result (Array simd.portable.vector_type.Coefficients 32#usize)
  := do
  let re1 ← simd.portable.ntt.outer_3_plus 0#usize 1#usize 2725464#i32 re
  let re2 ← simd.portable.ntt.outer_3_plus 2#usize 1#usize 1024112#i32 re1
  let re3 ← simd.portable.ntt.outer_3_plus 4#usize 1#usize (-1079900)#i32 re2
  let re4 ← simd.portable.ntt.outer_3_plus 6#usize 1#usize 3585928#i32 re3
  let re5 ← simd.portable.ntt.outer_3_plus 8#usize 1#usize (-549488)#i32 re4
  let re6 ←
    simd.portable.ntt.outer_3_plus 10#usize 1#usize (-1119584)#i32 re5
  let re7 ← simd.portable.ntt.outer_3_plus 12#usize 1#usize 2619752#i32 re6
  let re8 ←
    simd.portable.ntt.outer_3_plus 14#usize 1#usize (-2108549)#i32 re7
  let re9 ←
    simd.portable.ntt.outer_3_plus 16#usize 1#usize (-2118186)#i32 re8
  let re10 ←
    simd.portable.ntt.outer_3_plus 18#usize 1#usize (-3859737)#i32 re9
  let re11 ←
    simd.portable.ntt.outer_3_plus 20#usize 1#usize (-1399561)#i32 re10
  let re12 ←
    simd.portable.ntt.outer_3_plus 22#usize 1#usize (-3277672)#i32 re11
  let re13 ← simd.portable.ntt.outer_3_plus 24#usize 1#usize 1757237#i32 re12
  let re14 ←
    simd.portable.ntt.outer_3_plus 26#usize 1#usize (-19422)#i32 re13
  let re15 ← simd.portable.ntt.outer_3_plus 28#usize 1#usize 4010497#i32 re14
  simd.portable.ntt.outer_3_plus 30#usize 1#usize 280005#i32 re15

/-- [libcrux_iot_ml_dsa::simd::portable::ntt::ntt_at_layer_4]:
    Source: 'ml-dsa/src/simd/portable/ntt.rs', lines 244:0-256:1 -/
def simd.portable.ntt.ntt_at_layer_4
  (re : Array simd.portable.vector_type.Coefficients 32#usize) :
  Result (Array simd.portable.vector_type.Coefficients 32#usize)
  := do
  let re1 ← simd.portable.ntt.outer_3_plus 0#usize 2#usize 1826347#i32 re
  let re2 ← simd.portable.ntt.outer_3_plus 4#usize 2#usize 2353451#i32 re1
  let re3 ← simd.portable.ntt.outer_3_plus 8#usize 2#usize (-359251)#i32 re2
  let re4 ←
    simd.portable.ntt.outer_3_plus 12#usize 2#usize (-2091905)#i32 re3
  let re5 ← simd.portable.ntt.outer_3_plus 16#usize 2#usize 3119733#i32 re4
  let re6 ←
    simd.portable.ntt.outer_3_plus 20#usize 2#usize (-2884855)#i32 re5
  let re7 ← simd.portable.ntt.outer_3_plus 24#usize 2#usize 3111497#i32 re6
  simd.portable.ntt.outer_3_plus 28#usize 2#usize 2680103#i32 re7

/-- [libcrux_iot_ml_dsa::simd::portable::ntt::ntt_at_layer_5]:
    Source: 'ml-dsa/src/simd/portable/ntt.rs', lines 259:0-267:1 -/
def simd.portable.ntt.ntt_at_layer_5
  (re : Array simd.portable.vector_type.Coefficients 32#usize) :
  Result (Array simd.portable.vector_type.Coefficients 32#usize)
  := do
  let re1 ← simd.portable.ntt.outer_3_plus 0#usize 4#usize 237124#i32 re
  let re2 ← simd.portable.ntt.outer_3_plus 8#usize 4#usize (-777960)#i32 re1
  let re3 ← simd.portable.ntt.outer_3_plus 16#usize 4#usize (-876248)#i32 re2
  simd.portable.ntt.outer_3_plus 24#usize 4#usize 466468#i32 re3

/-- [libcrux_iot_ml_dsa::simd::portable::ntt::ntt_at_layer_6]:
    Source: 'ml-dsa/src/simd/portable/ntt.rs', lines 270:0-276:1 -/
def simd.portable.ntt.ntt_at_layer_6
  (re : Array simd.portable.vector_type.Coefficients 32#usize) :
  Result (Array simd.portable.vector_type.Coefficients 32#usize)
  := do
  let re1 ← simd.portable.ntt.outer_3_plus 0#usize 8#usize (-2608894)#i32 re
  simd.portable.ntt.outer_3_plus 16#usize 8#usize (-518909)#i32 re1

/-- [libcrux_iot_ml_dsa::simd::portable::ntt::ntt_at_layer_7]:
    Source: 'ml-dsa/src/simd/portable/ntt.rs', lines 279:0-284:1 -/
def simd.portable.ntt.ntt_at_layer_7
  (re : Array simd.portable.vector_type.Coefficients 32#usize) :
  Result (Array simd.portable.vector_type.Coefficients 32#usize)
  := do
  simd.portable.ntt.outer_3_plus 0#usize 16#usize 25847#i32 re

/-- [libcrux_iot_ml_dsa::simd::portable::ntt::ntt]:
    Source: 'ml-dsa/src/simd/portable/ntt.rs', lines 287:0-296:1 -/
def simd.portable.ntt.ntt
  (re : Array simd.portable.vector_type.Coefficients 32#usize) :
  Result (Array simd.portable.vector_type.Coefficients 32#usize)
  := do
  let re1 ← simd.portable.ntt.ntt_at_layer_7 re
  let re2 ← simd.portable.ntt.ntt_at_layer_6 re1
  let re3 ← simd.portable.ntt.ntt_at_layer_5 re2
  let re4 ← simd.portable.ntt.ntt_at_layer_4 re3
  let re5 ← simd.portable.ntt.ntt_at_layer_3 re4
  let re6 ← simd.portable.ntt.ntt_at_layer_2 re5
  let re7 ← simd.portable.ntt.ntt_at_layer_1 re6
  simd.portable.ntt.ntt_at_layer_0 re7

end libcrux_iot_ml_dsa
