[package]
name = "libcrux-iot-testutil"
version = "0.1.0"
edition = "2021"

[dependencies]
defmt = "0.3"
embassy-time = "0.3.2"
cortex-m = {version = "0.7.7", optional = true}

[features]
cortex-m = ["dep:cortex-m"]
