/*
 * SPDX-FileCopyrightText: 2025 Cryspen Sarl <info@cryspen.com>
 *
 * SPDX-License-Identifier: MIT or Apache-2.0
 *
 * This code was generated with the following revisions:
 * Charon: 637a6bc8a4c2a79875af5aa4e413c7ef3aa7f391
 * Eurydice: 5ca42bdb4309a18e332321ca9ae66607824428eb
 * Karamel: 4e64d915da3c172d1dfad805b8e1a46beff938bc
 * F*: unset
 * Libcrux: 936916cddc98fa7c87698a18d08336862d718614
 */

#ifndef libcrux_iot_mlkem1024_H
#define libcrux_iot_mlkem1024_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "libcrux_iot_core.h"

#define LIBCRUX_IOT_ML_KEM_MLKEM1024_VECTOR_U_COMPRESSION_FACTOR ((size_t)11U)

#define LIBCRUX_IOT_ML_KEM_MLKEM1024_C1_BLOCK_SIZE             \
  (LIBCRUX_IOT_ML_KEM_CONSTANTS_COEFFICIENTS_IN_RING_ELEMENT * \
   LIBCRUX_IOT_ML_KEM_MLKEM1024_VECTOR_U_COMPRESSION_FACTOR / (size_t)8U)

#define LIBCRUX_IOT_ML_KEM_MLKEM1024_RANK ((size_t)4U)

#define LIBCRUX_IOT_ML_KEM_MLKEM1024_C1_SIZE    \
  (LIBCRUX_IOT_ML_KEM_MLKEM1024_C1_BLOCK_SIZE * \
   LIBCRUX_IOT_ML_KEM_MLKEM1024_RANK)

#define LIBCRUX_IOT_ML_KEM_MLKEM1024_VECTOR_V_COMPRESSION_FACTOR ((size_t)5U)

#define LIBCRUX_IOT_ML_KEM_MLKEM1024_C2_SIZE                   \
  (LIBCRUX_IOT_ML_KEM_CONSTANTS_COEFFICIENTS_IN_RING_ELEMENT * \
   LIBCRUX_IOT_ML_KEM_MLKEM1024_VECTOR_V_COMPRESSION_FACTOR / (size_t)8U)

#define LIBCRUX_IOT_ML_KEM_MLKEM1024_CPA_PKE_CIPHERTEXT_SIZE \
  (LIBCRUX_IOT_ML_KEM_MLKEM1024_C1_SIZE + LIBCRUX_IOT_ML_KEM_MLKEM1024_C2_SIZE)

#define LIBCRUX_IOT_ML_KEM_MLKEM1024_T_AS_NTT_ENCODED_SIZE     \
  (LIBCRUX_IOT_ML_KEM_MLKEM1024_RANK *                         \
   LIBCRUX_IOT_ML_KEM_CONSTANTS_COEFFICIENTS_IN_RING_ELEMENT * \
   LIBCRUX_IOT_ML_KEM_CONSTANTS_BITS_PER_COEFFICIENT / (size_t)8U)

#define LIBCRUX_IOT_ML_KEM_MLKEM1024_CPA_PKE_PUBLIC_KEY_SIZE \
  (LIBCRUX_IOT_ML_KEM_MLKEM1024_T_AS_NTT_ENCODED_SIZE + (size_t)32U)

#define LIBCRUX_IOT_ML_KEM_MLKEM1024_CPA_PKE_SECRET_KEY_SIZE   \
  (LIBCRUX_IOT_ML_KEM_MLKEM1024_RANK *                         \
   LIBCRUX_IOT_ML_KEM_CONSTANTS_COEFFICIENTS_IN_RING_ELEMENT * \
   LIBCRUX_IOT_ML_KEM_CONSTANTS_BITS_PER_COEFFICIENT / (size_t)8U)

#define LIBCRUX_IOT_ML_KEM_MLKEM1024_ETA1 ((size_t)2U)

#define LIBCRUX_IOT_ML_KEM_MLKEM1024_ETA1_RANDOMNESS_SIZE \
  (LIBCRUX_IOT_ML_KEM_MLKEM1024_ETA1 * (size_t)64U)

#define LIBCRUX_IOT_ML_KEM_MLKEM1024_ETA2 ((size_t)2U)

#define LIBCRUX_IOT_ML_KEM_MLKEM1024_ETA2_RANDOMNESS_SIZE \
  (LIBCRUX_IOT_ML_KEM_MLKEM1024_ETA2 * (size_t)64U)

#define LIBCRUX_IOT_ML_KEM_MLKEM1024_IMPLICIT_REJECTION_HASH_INPUT_SIZE \
  (LIBCRUX_IOT_ML_KEM_CONSTANTS_SHARED_SECRET_SIZE +                    \
   LIBCRUX_IOT_ML_KEM_MLKEM1024_CPA_PKE_CIPHERTEXT_SIZE)

typedef Eurydice_arr_00 libcrux_iot_ml_kem_mlkem1024_MlKem1024Ciphertext;

typedef libcrux_iot_ml_kem_types_MlKemKeyPair_f7
    libcrux_iot_ml_kem_mlkem1024_MlKem1024KeyPair;

typedef Eurydice_arr_17 libcrux_iot_ml_kem_mlkem1024_MlKem1024PrivateKey;

typedef Eurydice_arr_00 libcrux_iot_ml_kem_mlkem1024_MlKem1024PublicKey;

#define LIBCRUX_IOT_ML_KEM_MLKEM1024_PRF_OUTPUT_SIZE1  \
  (LIBCRUX_IOT_ML_KEM_MLKEM1024_ETA1_RANDOMNESS_SIZE * \
   LIBCRUX_IOT_ML_KEM_MLKEM1024_RANK)

#define LIBCRUX_IOT_ML_KEM_MLKEM1024_PRF_OUTPUT_SIZE2  \
  (LIBCRUX_IOT_ML_KEM_MLKEM1024_ETA2_RANDOMNESS_SIZE * \
   LIBCRUX_IOT_ML_KEM_MLKEM1024_RANK)

#define LIBCRUX_IOT_ML_KEM_MLKEM1024_RANKED_BYTES_PER_RING_ELEMENT \
  (LIBCRUX_IOT_ML_KEM_MLKEM1024_RANK *                             \
   LIBCRUX_IOT_ML_KEM_CONSTANTS_BITS_PER_RING_ELEMENT / (size_t)8U)

#define LIBCRUX_IOT_ML_KEM_MLKEM1024_RANK_SQUARED \
  (LIBCRUX_IOT_ML_KEM_MLKEM1024_RANK * LIBCRUX_IOT_ML_KEM_MLKEM1024_RANK)

#define LIBCRUX_IOT_ML_KEM_MLKEM1024_SECRET_KEY_SIZE      \
  (LIBCRUX_IOT_ML_KEM_MLKEM1024_CPA_PKE_SECRET_KEY_SIZE + \
   LIBCRUX_IOT_ML_KEM_MLKEM1024_CPA_PKE_PUBLIC_KEY_SIZE + \
   LIBCRUX_IOT_ML_KEM_CONSTANTS_H_DIGEST_SIZE +           \
   LIBCRUX_IOT_ML_KEM_CONSTANTS_SHARED_SECRET_SIZE)

#if defined(__cplusplus)
}
#endif

#define libcrux_iot_mlkem1024_H_DEFINED
#endif /* libcrux_iot_mlkem1024_H */
