# SLOW_MODULES += Libcrux_ml_kem.Vector.Portable.Serialize.fst
# ADMIT_MODULES =

FSTAR_INCLUDE_DIRS_EXTRA += ../secrets \
	      $(shell git rev-parse --show-toplevel)/fstar-helpers/fstar-bitvec \

include $(shell git rev-parse --show-toplevel)/fstar-helpers/Makefile.base
