-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [libcrux_iot_sha3]: external functions.
-- This is a template file: rename it to "FunsExternal.lean" and fill the holes.
import Aeneas
import LibcruxIotSha3.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000
open libcrux_iot_sha3

/- [libcrux_secrets::int::public_integers::{libcrux_secrets::traits::Classify<T> for T}::classify]:
   Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libcrux-secrets-0.0.5/src/int/public_integers.rs', lines 27:4-27:29
   Name pattern: [libcrux_secrets::int::public_integers::{libcrux_secrets::traits::Classify<@T, @T>}::classify] -/
@[rust_fun
  "libcrux_secrets::int::public_integers::{libcrux_secrets::traits::Classify<@T, @T>}::classify"]
def libcrux_secrets.traits.Classify.Blanket.classify
  {T : Type} : T → Result T := .ok

/- [libcrux_secrets::int::{libcrux_secrets::int::CastOps for u64}::as_u32]:
   Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libcrux-secrets-0.0.5/src/int.rs', lines 83:12-83:34
   Name pattern: [libcrux_secrets::int::{libcrux_secrets::int::CastOps<u64>}::as_u32] -/
@[rust_fun
  "libcrux_secrets::int::{libcrux_secrets::int::CastOps<u64>}::as_u32"]
def U64.Insts.Libcrux_secretsIntCastOps.as_u32 : Std.U64 → Result Std.U32 := fun x => .ok (x.cast _)

/- [libcrux_secrets::int::{libcrux_secrets::int::CastOps for u32}::as_u64]:
   Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libcrux-secrets-0.0.5/src/int.rs', lines 91:12-91:34
   Name pattern: [libcrux_secrets::int::{libcrux_secrets::int::CastOps<u32>}::as_u64] -/
@[rust_fun
  "libcrux_secrets::int::{libcrux_secrets::int::CastOps<u32>}::as_u64"]
def U32.Insts.Libcrux_secretsIntCastOps.as_u64 : Std.U32 → Result Std.U64 := fun x => .ok (x.cast _)
