-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [libcrux_iot_sha3]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- [core::fmt::builders::DebugTuple]
   Source: '/rustc/library/core/src/fmt/builders.rs', lines 289:0-289:33
   Name pattern: [core::fmt::builders::DebugTuple] -/
@[rust_type "core::fmt::builders::DebugTuple"]
axiom core.fmt.builders.DebugTuple : Type

