-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [libcrux_iot_sha3]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

namespace libcrux_iot_sha3

/- [libcrux_iot_sha3::lane::Lane2U32]
   Source: 'sha3/src/lane.rs', lines 7:0-7:30 -/
@[reducible]
def lane.Lane2U32 := Array Std.U32 2#usize

/- [libcrux_iot_sha3::state::KeccakState]
   Source: 'sha3/src/state.rs', lines 12:0-17:1 -/
structure state.KeccakState where
  st : Array lane.Lane2U32 25#usize
  c : Array lane.Lane2U32 5#usize
  d : Array lane.Lane2U32 5#usize
  i : Std.Usize

/- [libcrux_iot_sha3::keccak::KeccakXofState]
   Source: 'sha3/src/keccak.rs', lines 13:0-24:1 -/
structure keccak.KeccakXofState (RATE : Std.Usize) where
  inner : state.KeccakState
  buf : Array Std.U8 RATE
  buf_len : Std.Usize
  sponge : Bool

/- [libcrux_iot_sha3::Algorithm]
   Source: 'sha3/src/lib.rs', lines 27:0-39:1 -/
@[discriminant u32 [1,2,3,4]]
inductive Algorithm where
| Sha224 : Algorithm
| Sha256 : Algorithm
| Sha384 : Algorithm
| Sha512 : Algorithm

/- [libcrux_iot_sha3::portable::KeccakState]
   Source: 'sha3/src/lib.rs', lines 208:4-210:5 -/
structure portable.KeccakState where
  state : state.KeccakState

/- Trait declaration: [libcrux_iot_sha3::portable::incremental::private::Sealed]
   Source: 'sha3/src/lib.rs', lines 254:12-254:31 -/
structure portable.incremental.private.Sealed (Self : Type) where

/- [libcrux_iot_sha3::portable::incremental::Shake128Xof]
   Source: 'sha3/src/lib.rs', lines 262:8-264:9 -/
structure portable.incremental.Shake128Xof where
  state : keccak.KeccakXofState 168#usize

/- [libcrux_iot_sha3::portable::incremental::Shake256Xof]
   Source: 'sha3/src/lib.rs', lines 267:8-269:9 -/
structure portable.incremental.Shake256Xof where
  state : keccak.KeccakXofState 136#usize

/- Trait declaration: [libcrux_iot_sha3::portable::incremental::Xof]
   Source: 'sha3/src/lib.rs', lines 272:8-284:9 -/
structure portable.incremental.Xof (Self : Type) (RATE : Std.Usize) where
  privateSealedInst : portable.incremental.private.Sealed Self
  new : Result Self
  absorb : Self → Slice Std.U8 → Result Self
  absorb_final : Self → Slice Std.U8 → Result Self
  squeeze : Self → Slice Std.U8 → Result (Self × (Slice Std.U8))

end libcrux_iot_sha3
