/* automatically generated by rust-bindgen 0.71.1 */

pub const KYBER_K: u32 = 4;
pub const KYBER_N: u32 = 256;
pub const KYBER_Q: u32 = 3329;
pub const KYBER_ETA: u32 = 2;
pub const KYBER_SYMBYTES: u32 = 32;
pub const KYBER_SSBYTES: u32 = 32;
pub const KYBER_POLYBYTES: u32 = 384;
pub const KYBER_POLYVECBYTES: u32 = 1536;
pub const KYBER_POLYCOMPRESSEDBYTES: u32 = 160;
pub const KYBER_POLYVECCOMPRESSEDBYTES: u32 = 1408;
pub const KYBER_INDCPA_MSGBYTES: u32 = 32;
pub const KYBER_INDCPA_PUBLICKEYBYTES: u32 = 1568;
pub const KYBER_INDCPA_SECRETKEYBYTES: u32 = 1536;
pub const KYBER_INDCPA_BYTES: u32 = 1568;
pub const KYBER_PUBLICKEYBYTES: u32 = 1568;
pub const KYBER_SECRETKEYBYTES: u32 = 3168;
pub const KYBER_CIPHERTEXTBYTES: u32 = 1568;
pub const CRYPTO_SECRETKEYBYTES: u32 = 3168;
pub const CRYPTO_PUBLICKEYBYTES: u32 = 1568;
pub const CRYPTO_CIPHERTEXTBYTES: u32 = 1568;
pub const CRYPTO_BYTES: u32 = 32;
pub const CRYPTO_ALGNAME: &[u8; 10] = b"Kyber1024\0";
unsafe extern "C" {
    pub fn crypto_kem_keypair(
        pk: *mut ::core::ffi::c_uchar,
        sk: *mut ::core::ffi::c_uchar,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn crypto_kem_enc(
        ct: *mut ::core::ffi::c_uchar,
        ss: *mut ::core::ffi::c_uchar,
        pk: *const ::core::ffi::c_uchar,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn crypto_kem_dec(
        ss: *mut ::core::ffi::c_uchar,
        ct: *const ::core::ffi::c_uchar,
        sk: *const ::core::ffi::c_uchar,
    ) -> ::core::ffi::c_int;
}
