name: Build for all boards

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "*"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board_directory: [
                          libcrux-nucleo-l4r5zi,
                          libcrux-nrf52840,
                          libcrux-nrf52810,
                          libcrux-nrf52832,
                          libcrux-nrf5340,
                         ]

    steps:
      - uses: actions/checkout@v4

      - name: Install GNU ARM Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1.8.0
        with:
          release: 13.2.Rel1
             
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: thumbv7em-none-eabihf,thumbv7em-none-eabi,thumbv8m.main-none-eabihf

      - name: Install flip-link
        run: cargo install flip-link

      - name: Build
        working-directory: ${{ matrix.board_directory }}
        run: cargo build --verbose
