name: Build for all boards

permissions: {}

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "*"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board_directory: [
                          libcrux-nucleo-l4r5zi,
                         ]

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          persist-credentials: false

      - name: Install GNU ARM Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: 13.2.Rel1
             
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: thumbv7em-none-eabihf

      - name: Install flip-link
        run: cargo install flip-link

      - name: Build
        working-directory: ${{ matrix.board_directory }}
        run: cargo build --release --verbose
