name: ML-DSA - Build & Test

permissions: {}

on:
  merge_group:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "*"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: ${{ github.event_name != 'merge_group' }}
    strategy:
      fail-fast: false
      matrix:
        # These are all arm64, of course, but at least we can test on
        # some ARM architectures with different stack size defaults
        # etc
        os:
          - ubuntu-24.04-arm
          - macos-latest

    runs-on:  ${{ matrix.os }}
    defaults:
      run:
        shell: bash
        working-directory: libcrux-iot/ml-dsa

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      # Build ...
      - name: 🔨 Build
        run: |
          rustc --print=cfg
          cargo build --verbose

      - name: 🔨 Build Release
        run: cargo build --verbose --release

      - name: 🏃🏻 Asan MacOS
        if: ${{ matrix.os == 'macos-latest' }}
        run: RUSTDOCFLAGS=-Zsanitizer=address RUSTFLAGS=-Zsanitizer=address cargo +nightly test --release --target aarch64-apple-darwin

      # Test ML-DSA
      - name: 🏃🏻‍♀️ Test
        run: |
          cargo clean
          cargo test --verbose --features acvp

      - name: 🏃🏻‍♀️ Test Release
        run: |
          cargo clean
          cargo test --verbose --release --features acvp

      - name: 🏃🏻‍♀️ Check Secret-Independence
        run: |
          cargo clean
          cargo check -F check-secret-independence --verbose

      # Test ML-DSA (stack optimized)
      - name: 🏃🏻‍♀️ Test
        run: |
          cargo clean
          cargo test --verbose --features acvp,stack

      - name: 🏃🏻‍♀️ Test Release
        run: |
          cargo clean
          cargo test --verbose --release --features acvp,stack

      - name: 🏃🏻‍♀️ Check Secret-Independence
        run: |
          cargo clean
          cargo check -F check-secret-independence,stack --verbose
          
      # Benchmarks
      - name: 🔨 Build Benchmarks
        run: |
          cargo clean
          cargo bench --no-run

  valgrind-ct-test:
    if: ${{ github.event_name != 'merge_group' }}
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        features:
          - "--features check-secret-independence,acvp"
          - "--features check-secret-independence,acvp,stack"
    defaults:
      run:
        shell: bash
        working-directory: libcrux-iot/ml-dsa
    env:
      RUSTFLAGS: '--cfg valgrind_ct_test'
      # don't use --track-origins here, as that makes the tests even slower
      CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_RUNNER: 'valgrind --tool=memcheck --error-exitcode=1'

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install valgrind
        run: sudo apt-get update && sudo apt-get install -y valgrind

      # Using nextest significantly speeds up the tests under valgrind
      - name: Install cargo nextest
        uses: taiki-e/install-action@cargo-nextest

      - name: 🏃🏻‍♀️ Test under valgrind
        # only run the acvp tests, as the full test suite would take too long under valgrind
        run: cargo nextest run --verbose --cargo-profile release-debug ${{ matrix.features }} --test acvp

  mldsa-build-test-status:
    if: ${{ always() }}
    needs: [build, valgrind-ct-test]
    runs-on: ubuntu-latest
    steps:
      - name: Successful
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failing
        if: ${{ (contains(needs.*.result, 'failure')) }}
        run: exit 1
